export interface PolicyIssue {
  id: string;
  category: string;
  title: string;
  prompt: string;
  description: string;
  tags: string[];
}

export const POLICY_ISSUES: PolicyIssue[] = [
  {
    id: "healthcare-coverage",
    category: "Healthcare",
    title: "Healthcare Coverage",
    prompt: "How much should the government be involved in ensuring all Americans have access to healthcare coverage?",
    description: "Covers public insurance programs, mandates, and the role of private insurers.",
    tags: ["healthcare", "insurance", "public-health"],
  },
  {
    id: "drug-pricing",
    category: "Healthcare",
    title: "Prescription Drug Pricing",
    prompt: "How much should the government regulate prescription drug prices?",
    description: "Includes Medicare negotiation, price caps, and pharmaceutical market rules.",
    tags: ["healthcare", "pharma", "regulation"],
  },
  {
    id: "public-education-funding",
    category: "Education",
    title: "Public School Funding",
    prompt: "How much should the federal government control funding for public K–12 schools?",
    description: "Relates to federal vs. local control, standardized testing, and school resource equity.",
    tags: ["education", "schools", "funding"],
  },
  {
    id: "student-loan-policy",
    category: "Education",
    title: "Student Loan Policy",
    prompt: "How involved should the government be in managing or forgiving student loan debt?",
    description: "Covers forgiveness programs, income-driven repayment, and federal lending role.",
    tags: ["education", "debt", "higher-education"],
  },
  {
    id: "minimum-wage",
    category: "Labor & Economy",
    title: "Federal Minimum Wage",
    prompt: "How much should the federal government set or raise the national minimum wage?",
    description: "Relates to worker pay floors, cost-of-living adjustments, and business impact.",
    tags: ["labor", "wages", "economy"],
  },
  {
    id: "union-rights",
    category: "Labor & Economy",
    title: "Labor Union Rights",
    prompt: "How much should the government protect and support the rights of workers to organize and bargain collectively?",
    description: "Includes collective bargaining protections, right-to-work laws, and strike rules.",
    tags: ["labor", "unions", "workers"],
  },
  {
    id: "corporate-taxation",
    category: "Labor & Economy",
    title: "Corporate Taxation",
    prompt: "How much should the government tax corporate profits?",
    description: "Relates to corporate tax rates, loopholes, offshore profits, and revenue for public programs.",
    tags: ["taxes", "corporations", "economy"],
  },
  {
    id: "wealth-tax",
    category: "Labor & Economy",
    title: "Wealth & Income Taxes",
    prompt: "How much should the government tax high-income earners and accumulated wealth?",
    description: "Covers progressive taxation, capital gains taxes, and estate taxes.",
    tags: ["taxes", "inequality", "economy"],
  },
  {
    id: "climate-policy",
    category: "Environment",
    title: "Climate & Emissions Policy",
    prompt: "How much should the government regulate carbon emissions and invest in climate change mitigation?",
    description: "Includes carbon taxes, clean energy mandates, international agreements, and emission caps.",
    tags: ["environment", "climate", "energy"],
  },
  {
    id: "public-lands",
    category: "Environment",
    title: "Public Land Management",
    prompt: "How much control should the federal government have over public lands, including national parks and forests?",
    description: "Covers drilling rights, conservation, grazing permits, and land transfer to states.",
    tags: ["environment", "land", "conservation"],
  },
  {
    id: "gun-background-checks",
    category: "Gun Policy",
    title: "Firearm Background Checks",
    prompt: "How much should the government expand background check requirements for firearm purchases?",
    description: "Includes universal checks, private sales, gun shows, and mental health records.",
    tags: ["guns", "safety", "regulation"],
  },
  {
    id: "assault-weapons",
    category: "Gun Policy",
    title: "Assault Weapon Regulations",
    prompt: "How much should the government restrict the sale and ownership of military-style assault weapons?",
    description: "Relates to bans, feature restrictions, grandfathering existing owners, and enforcement.",
    tags: ["guns", "regulation", "safety"],
  },
  {
    id: "border-enforcement",
    category: "Immigration",
    title: "Border Enforcement",
    prompt: "How much should the government increase enforcement and physical barriers at the southern border?",
    description: "Covers border patrol funding, wall construction, technology, and asylum processing.",
    tags: ["immigration", "border", "enforcement"],
  },
  {
    id: "immigration-pathways",
    category: "Immigration",
    title: "Legal Immigration Pathways",
    prompt: "How much should the government expand legal pathways for immigrants seeking to live and work in the U.S.?",
    description: "Includes visa programs, merit-based systems, refugee quotas, and family reunification.",
    tags: ["immigration", "legal", "visas"],
  },
  {
    id: "social-security",
    category: "Social Programs",
    title: "Social Security",
    prompt: "How much should the government expand or protect Social Security retirement benefits?",
    description: "Relates to benefit levels, retirement age, payroll tax caps, and long-term solvency.",
    tags: ["social-security", "retirement", "elderly"],
  },
  {
    id: "welfare-programs",
    category: "Social Programs",
    title: "Welfare & Safety Net Programs",
    prompt: "How much should the government expand social safety net programs like food assistance and housing aid?",
    description: "Covers SNAP, TANF, Medicaid, Section 8, work requirements, and eligibility rules.",
    tags: ["welfare", "poverty", "social-programs"],
  },
  {
    id: "housing-policy",
    category: "Social Programs",
    title: "Affordable Housing",
    prompt: "How much should the federal government invest in and regulate affordable housing?",
    description: "Includes public housing, rental assistance, zoning reform, and first-time buyer programs.",
    tags: ["housing", "affordability", "urban"],
  },
  {
    id: "policing-reform",
    category: "Criminal Justice",
    title: "Policing & Law Enforcement",
    prompt: "How much should the government increase oversight and reform of police departments?",
    description: "Covers qualified immunity, civilian review boards, federal standards, and use-of-force rules.",
    tags: ["police", "reform", "criminal-justice"],
  },
  {
    id: "incarceration-policy",
    category: "Criminal Justice",
    title: "Incarceration & Sentencing",
    prompt: "How much should the government reform mandatory minimum sentencing and reduce incarceration rates?",
    description: "Includes drug sentencing, prison conditions, recidivism programs, and rehabilitation.",
    tags: ["prison", "sentencing", "criminal-justice"],
  },
  {
    id: "surveillance-privacy",
    category: "Civil Liberties",
    title: "Government Surveillance & Privacy",
    prompt: "How much should the government limit its own surveillance and data collection on citizens?",
    description: "Covers NSA programs, facial recognition, warrantless searches, and digital privacy laws.",
    tags: ["privacy", "surveillance", "civil-liberties"],
  },
  {
    id: "campaign-finance",
    category: "Democracy & Elections",
    title: "Campaign Finance Reform",
    prompt: "How much should the government restrict private money in political campaigns?",
    description: "Relates to Citizens United, PAC regulations, dark money disclosure, and public financing.",
    tags: ["elections", "money", "democracy"],
  },
  {
    id: "voting-access",
    category: "Democracy & Elections",
    title: "Voting Access",
    prompt: "How much should the government expand access to voting, including registration and mail-in options?",
    description: "Covers automatic registration, early voting, voter ID laws, and mail-in ballots.",
    tags: ["voting", "elections", "democracy"],
  },
  {
    id: "military-spending",
    category: "Defense & Foreign Policy",
    title: "Military Spending",
    prompt: "How much should the government increase the defense budget and military capabilities?",
    description: "Includes defense contractor spending, new weapons systems, troop levels, and overseas bases.",
    tags: ["military", "defense", "spending"],
  },
  {
    id: "foreign-aid",
    category: "Defense & Foreign Policy",
    title: "Foreign Aid",
    prompt: "How much should the government provide in foreign aid and international development funding?",
    description: "Relates to humanitarian aid, military assistance to allies, and diplomatic funding.",
    tags: ["foreign-policy", "aid", "international"],
  },
  {
    id: "trade-policy",
    category: "Defense & Foreign Policy",
    title: "Trade & Tariffs",
    prompt: "How much should the government use tariffs and trade restrictions to protect American industries?",
    description: "Covers protectionism, free trade agreements, China policy, and manufacturing jobs.",
    tags: ["trade", "tariffs", "economy"],
  },
  {
    id: "tech-regulation",
    category: "Technology",
    title: "Big Tech Regulation",
    prompt: "How much should the government regulate large technology companies and social media platforms?",
    description: "Includes antitrust enforcement, data privacy, content moderation liability, and market power.",
    tags: ["tech", "antitrust", "regulation"],
  },
  {
    id: "net-neutrality",
    category: "Technology",
    title: "Internet & Net Neutrality",
    prompt: "How much should the government regulate internet service providers to ensure equal access to all online content?",
    description: "Covers net neutrality rules, ISP practices, broadband access, and FCC authority.",
    tags: ["internet", "net-neutrality", "tech"],
  },
  {
    id: "infrastructure",
    category: "Infrastructure",
    title: "Federal Infrastructure Investment",
    prompt: "How much should the government invest in rebuilding and expanding national infrastructure?",
    description: "Includes roads, bridges, rail, broadband, water systems, and the electrical grid.",
    tags: ["infrastructure", "investment", "public-works"],
  },
  {
    id: "energy-transition",
    category: "Infrastructure",
    title: "Energy Transition & Clean Power",
    prompt: "How much should the government subsidize and mandate a transition to renewable energy sources?",
    description: "Covers solar/wind subsidies, fossil fuel phase-outs, grid modernization, and EV incentives.",
    tags: ["energy", "renewables", "environment"],
  },
  {
    id: "banking-regulation",
    category: "Labor & Economy",
    title: "Banking & Financial Regulation",
    prompt: "How much should the government regulate banks and financial institutions to prevent systemic risk?",
    description: "Includes Dodd-Frank rules, consumer protections, cryptocurrency oversight, and too-big-to-fail policy.",
    tags: ["banking", "finance", "regulation"],
  },
];

export const ISSUE_CATEGORIES = [...new Set(POLICY_ISSUES.map(i => i.category))];

export const RESPONSE_LABELS: Record<number, string> = {
  1: "Much Less",
  2: "Somewhat Less",
  3: "About the Same",
  4: "Somewhat More",
  5: "Much More",
};

export const RESPONSE_DESCRIPTIONS: Record<number, string> = {
  1: "Strongly decrease government involvement",
  2: "Somewhat decrease government involvement",
  3: "Keep government involvement roughly the same",
  4: "Somewhat increase government involvement",
  5: "Strongly increase government involvement",
};
