import { db } from "./db";
import { sql } from "drizzle-orm";

function log(msg: string) {
  const time = new Date().toLocaleTimeString("en-US", { hour12: false });
  console.log(`${time} [lobby-seed] ${msg}`);
}

type TopPac = { name: string; amount: string; partyLean: "D" | "R" | "Split" };
type TopCandidate = { name: string; party: string; office: string; totalReceived: string };
type InterestBreakdown = { label: string; pct: number };

type SectorEntry = {
  name: string;
  tag: string;
  acronym?: string;
  description: string;
  category: string;
  sentiment: string;
  spendRange: string;
  partySplitDem: number;
  partySplitRep: number;
  website: string;
  headquarters: string;
  industry: string;
  influenceScore: number;
  dataSourceName: string;
  dataSourceUrl: string;
  topPacs: TopPac[];
  topCandidates: TopCandidate[];
  interestBreakdown: InterestBreakdown[];
};

const SECTORS: SectorEntry[] = [
  {
    name: "National Rifle Association",
    tag: "NRA",
    acronym: "NRA",
    description: "The National Rifle Association is the United States' most powerful gun-rights lobbying organization, spending $10–$50M annually to block firearm regulations and elect pro-gun candidates. It opposes universal background checks, assault-weapons bans, red-flag laws, and safe-storage mandates. The NRA's A–F candidate grading system and primary endorsements make it one of the most feared single-issue lobbies in American politics.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$10M–$50M",
    partySplitDem: 5,
    partySplitRep: 95,
    website: "https://www.nra.org",
    headquarters: "Fairfax, VA",
    industry: "gun_rights",
    influenceScore: -40,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/national-rifle-assn/summary?id=d000000082",
    topPacs: [
      { name: "NRA Political Victory Fund", amount: "$28.4M", partyLean: "R" },
      { name: "NRA Institute for Legislative Action", amount: "$14.2M", partyLean: "R" },
      { name: "Gun Owners of America PAC", amount: "$3.1M", partyLean: "R" },
      { name: "National Shooting Sports Foundation PAC", amount: "$2.4M", partyLean: "R" },
      { name: "Safari Club International PAC", amount: "$1.8M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", office: "President", totalReceived: "$30.0M" },
      { name: "Mitt Romney", party: "R", office: "U.S. Senate", totalReceived: "$13.6M" },
      { name: "Thom Tillis", party: "R", office: "U.S. Senate", totalReceived: "$4.4M" },
      { name: "Richard Burr", party: "R", office: "U.S. Senate", totalReceived: "$3.9M" },
      { name: "Tom Cotton", party: "R", office: "U.S. Senate", totalReceived: "$3.0M" },
    ],
    interestBreakdown: [
      { label: "Background Check Opposition", pct: 30 },
      { label: "Assault Weapons Ban Opposition", pct: 26 },
      { label: "Red-Flag Law Opposition", pct: 20 },
      { label: "Concealed Carry Reciprocity", pct: 14 },
      { label: "Hunting & Second Amendment Rights", pct: 10 },
    ],
  },
  {
    name: "American Israel Public Affairs Committee",
    tag: "AIPAC",
    acronym: "AIPAC",
    description: "AIPAC is the premier pro-Israel lobbying organization in the United States, mobilizing hundreds of millions of dollars in campaign contributions to support candidates who back strong U.S.–Israel relations and military aid. It was transformed by the 2022 Citizens United ruling into a direct super PAC spender, becoming one of the largest outside spenders in recent election cycles. AIPAC opposes conditioning U.S. aid to Israel and works to ensure no daylight between Washington and Jerusalem on security policy.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$14M–$100M+",
    partySplitDem: 40,
    partySplitRep: 60,
    website: "https://www.aipac.org",
    headquarters: "Washington, DC",
    industry: "foreign_affairs",
    influenceScore: -10,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-israel-public-affairs-cmte/summary?id=d000000052",
    topPacs: [
      { name: "United Democracy Project (AIPAC Super PAC)", amount: "$72.0M", partyLean: "Split" },
      { name: "AIPAC PAC", amount: "$14.8M", partyLean: "Split" },
      { name: "Jewish Federations of North America PAC", amount: "$2.1M", partyLean: "D" },
      { name: "American Jewish Committee PAC", amount: "$1.4M", partyLean: "Split" },
      { name: "Zionist Organization of America PAC", amount: "$0.9M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Steny Hoyer", party: "D", office: "U.S. House", totalReceived: "$1.8M" },
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$1.6M" },
      { name: "Bob Menendez", party: "D", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "John Cornyn", party: "R", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Marco Rubio", party: "R", office: "U.S. Senate", totalReceived: "$1.1M" },
    ],
    interestBreakdown: [
      { label: "U.S.–Israel Military Aid", pct: 35 },
      { label: "Iran Sanctions & Nuclear Policy", pct: 28 },
      { label: "Opposing Palestinian Statehood Conditions", pct: 18 },
      { label: "Middle East Diplomacy", pct: 12 },
      { label: "Anti-BDS Legislation", pct: 7 },
    ],
  },
  {
    name: "U.S. Chamber of Commerce",
    tag: "USCC",
    acronym: "USCC",
    description: "The U.S. Chamber of Commerce is the single largest lobbying organization in American history, spending $60–$100M+ annually on federal lobbying alone. It represents three million businesses and fights against minimum wage increases, climate regulations, consumer financial protections, and labor organizing rights. The Chamber has been the decisive force in defeating or weakening virtually every major pro-worker and pro-environment law of the past three decades.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$60M–$100M+",
    partySplitDem: 18,
    partySplitRep: 82,
    website: "https://www.uschamber.com",
    headquarters: "Washington, DC",
    industry: "business",
    influenceScore: -45,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/us-chamber-of-commerce/summary?id=d000019798",
    topPacs: [
      { name: "U.S. Chamber of Commerce (direct lobbying)", amount: "$84.0M", partyLean: "R" },
      { name: "Chamber of Commerce of the USA PAC", amount: "$6.4M", partyLean: "R" },
      { name: "Business Roundtable", amount: "$29.0M", partyLean: "R" },
      { name: "National Association of Manufacturers PAC", amount: "$4.8M", partyLean: "R" },
      { name: "Business-Industry PAC", amount: "$4.2M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Rob Portman", party: "R", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "John Cornyn", party: "R", office: "U.S. Senate", totalReceived: "$1.0M" },
      { name: "Thom Tillis", party: "R", office: "U.S. Senate", totalReceived: "$880K" },
      { name: "Steve Scalise", party: "R", office: "U.S. House", totalReceived: "$760K" },
    ],
    interestBreakdown: [
      { label: "Deregulation & Anti-Regulatory Policy", pct: 32 },
      { label: "Corporate Tax Cuts", pct: 24 },
      { label: "Anti-Labor (Union Opposition)", pct: 20 },
      { label: "Trade & Tariff Policy", pct: 14 },
      { label: "Climate & Environment Rules", pct: 10 },
    ],
  },
  {
    name: "AARP",
    tag: "AARP",
    acronym: "AARP",
    description: "AARP (formerly the American Association of Retired Persons) is the largest membership organization in the U.S. with 38 million members, spending $20–$50M annually to protect Social Security, Medicare, and prescription drug pricing. It successfully pushed for Medicare drug price negotiation in the Inflation Reduction Act of 2022. AARP is one of the most powerful bipartisan lobbies given the high voter turnout of seniors.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$50M",
    partySplitDem: 60,
    partySplitRep: 40,
    website: "https://www.aarp.org",
    headquarters: "Washington, DC",
    industry: "senior_citizens",
    influenceScore: 25,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/aarp/summary?id=d000023726",
    topPacs: [
      { name: "AARP Services Inc. Lobbying", amount: "$38.0M", partyLean: "Split" },
      { name: "AARP Action Fund", amount: "$4.2M", partyLean: "D" },
      { name: "Alliance for Retired Americans PAC", amount: "$2.8M", partyLean: "D" },
      { name: "National Committee to Preserve SS & Medicare", amount: "$2.2M", partyLean: "D" },
      { name: "Senior Citizens League", amount: "$1.1M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Patty Murray", party: "D", office: "U.S. Senate", totalReceived: "$920K" },
      { name: "Chuck Grassley", party: "R", office: "U.S. Senate", totalReceived: "$840K" },
      { name: "Ron Wyden", party: "D", office: "U.S. Senate", totalReceived: "$780K" },
      { name: "Richard Neal", party: "D", office: "U.S. House", totalReceived: "$720K" },
      { name: "Mike Crapo", party: "R", office: "U.S. Senate", totalReceived: "$640K" },
    ],
    interestBreakdown: [
      { label: "Medicare & Prescription Drug Pricing", pct: 35 },
      { label: "Social Security Solvency", pct: 28 },
      { label: "Long-Term Care & Medicaid", pct: 18 },
      { label: "Age Discrimination & Elder Abuse", pct: 12 },
      { label: "Retirement Savings Rules", pct: 7 },
    ],
  },
  {
    name: "AFL-CIO",
    tag: "AFLCIO",
    acronym: "AFL-CIO",
    description: "The American Federation of Labor and Congress of Industrial Organizations is the largest federation of unions in the U.S., representing 12.5 million workers across 60 unions. It spends $50–$90M per election cycle on campaign activity for candidates who support workers' rights, minimum wage increases, and collective bargaining protections. The AFL-CIO has been the backbone of Democratic electoral infrastructure for decades.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$50M–$90M",
    partySplitDem: 92,
    partySplitRep: 8,
    website: "https://aflcio.org",
    headquarters: "Washington, DC",
    industry: "labor",
    influenceScore: 35,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/afl-cio/summary?id=d000000088",
    topPacs: [
      { name: "AFL-CIO Workers' Voices PAC", amount: "$22.4M", partyLean: "D" },
      { name: "AFL-CIO COPE (political fund)", amount: "$18.6M", partyLean: "D" },
      { name: "Teamsters PAC", amount: "$7.4M", partyLean: "D" },
      { name: "United Steelworkers PAC", amount: "$4.8M", partyLean: "D" },
      { name: "Communications Workers of America PAC", amount: "$4.2M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.8M" },
      { name: "Sherrod Brown", party: "D", office: "U.S. Senate", totalReceived: "$1.6M" },
      { name: "Patty Murray", party: "D", office: "U.S. Senate", totalReceived: "$1.3M" },
      { name: "Bernie Sanders", party: "D", office: "U.S. Senate", totalReceived: "$1.1M" },
      { name: "Bob Casey Jr", party: "D", office: "U.S. Senate", totalReceived: "$980K" },
    ],
    interestBreakdown: [
      { label: "Collective Bargaining & PRO Act", pct: 32 },
      { label: "Minimum Wage & Benefits", pct: 26 },
      { label: "Workplace Safety (OSHA)", pct: 18 },
      { label: "Pension & Retirement Security", pct: 14 },
      { label: "Trade & Outsourcing", pct: 10 },
    ],
  },
  {
    name: "Pharmaceutical Research & Manufacturers of America",
    tag: "PHRMA",
    acronym: "PhRMA",
    description: "PhRMA is the primary trade association for major drug companies, spending $200–$300M annually — making pharma the top lobbying sector in Washington. It aggressively blocks Medicare drug price negotiation, opposes importation of cheaper drugs from Canada, and fights patent reform that would allow earlier generic competition. PhRMA's campaign against the Inflation Reduction Act's drug pricing provisions cost $50M+ in a single year.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$200M–$300M",
    partySplitDem: 52,
    partySplitRep: 48,
    website: "https://www.phrma.org",
    headquarters: "Washington, DC",
    industry: "pharma",
    influenceScore: -35,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/pharmaceutical-rsrch-mfrs-of-america/summary?id=d000000504",
    topPacs: [
      { name: "PhRMA PAC", amount: "$8.4M", partyLean: "Split" },
      { name: "Pfizer Inc PAC", amount: "$6.2M", partyLean: "Split" },
      { name: "Eli Lilly & Co PAC", amount: "$5.6M", partyLean: "Split" },
      { name: "AbbVie Inc PAC", amount: "$4.9M", partyLean: "R" },
      { name: "Johnson & Johnson PAC", amount: "$4.4M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$1.3M" },
      { name: "Kyrsten Sinema", party: "D", office: "U.S. Senate", totalReceived: "$920K" },
      { name: "Chuck Grassley", party: "R", office: "U.S. Senate", totalReceived: "$860K" },
      { name: "Pat Toomey", party: "R", office: "U.S. Senate", totalReceived: "$820K" },
      { name: "Joe Manchin", party: "D", office: "U.S. Senate", totalReceived: "$760K" },
    ],
    interestBreakdown: [
      { label: "Drug Pricing & Medicare Negotiation", pct: 34 },
      { label: "FDA Regulation & Approval", pct: 22 },
      { label: "Patent & Exclusivity Protection", pct: 20 },
      { label: "Drug Importation Opposition", pct: 14 },
      { label: "Medicaid Rebate Policy", pct: 10 },
    ],
  },
  {
    name: "National Association of Realtors",
    tag: "NAR",
    acronym: "NAR",
    description: "The National Association of Realtors is historically the largest PAC donor in U.S. federal elections, consistently spending $60–$80M per cycle. It lobbies to protect the mortgage interest deduction, oppose rent control and affordable housing mandates, influence zoning policy, and preserve favorable capital-gains treatment for property sales. NAR's political arm gives to both parties in roughly equal measure to maximize influence across the aisle.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$60M–$80M",
    partySplitDem: 46,
    partySplitRep: 54,
    website: "https://www.nar.realtor",
    headquarters: "Chicago, IL",
    industry: "real_estate",
    influenceScore: -15,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/national-assn-of-realtors/summary?id=d000000062",
    topPacs: [
      { name: "National Assn of Realtors PAC (RPAC)", amount: "$62.4M", partyLean: "Split" },
      { name: "National Assn of Home Builders PAC", amount: "$6.4M", partyLean: "R" },
      { name: "Mortgage Bankers Assn PAC", amount: "$3.2M", partyLean: "Split" },
      { name: "CBRE Group PAC", amount: "$2.6M", partyLean: "Split" },
      { name: "Apartment Investment PAC", amount: "$2.1M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Kevin McCarthy", party: "R", office: "U.S. House", totalReceived: "$980K" },
      { name: "Steny Hoyer", party: "D", office: "U.S. House", totalReceived: "$860K" },
      { name: "David Scott", party: "D", office: "U.S. House", totalReceived: "$740K" },
      { name: "Roger Williams", party: "R", office: "U.S. House", totalReceived: "$680K" },
      { name: "Bob Menendez", party: "D", office: "U.S. Senate", totalReceived: "$620K" },
    ],
    interestBreakdown: [
      { label: "Mortgage Interest Deduction", pct: 28 },
      { label: "Zoning & Land Use Policy", pct: 24 },
      { label: "Housing Finance (GSE Reform)", pct: 20 },
      { label: "Capital Gains on Home Sales", pct: 16 },
      { label: "Affordable Housing & Rent Control", pct: 12 },
    ],
  },
  {
    name: "American Medical Association",
    tag: "AMA",
    acronym: "AMA",
    description: "The American Medical Association is the largest professional association of physicians in the U.S., spending $20–$40M annually to shape healthcare payment policy, physician autonomy rules, and scope-of-practice laws. The AMA historically blocked universal healthcare proposals including Medicare itself until 1965 and continues to protect physician reimbursement rates and oppose nurse practitioner scope expansions that would reduce medical costs.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$20M–$40M",
    partySplitDem: 58,
    partySplitRep: 42,
    website: "https://www.ama-assn.org",
    headquarters: "Chicago, IL",
    industry: "healthcare",
    influenceScore: -8,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-medical-assn/summary?id=d000000068",
    topPacs: [
      { name: "AMA Political Action Committee (AMPAC)", amount: "$14.8M", partyLean: "Split" },
      { name: "American College of Surgeons PAC", amount: "$3.2M", partyLean: "Split" },
      { name: "American Academy of Pediatrics PAC", amount: "$2.4M", partyLean: "D" },
      { name: "American College of Physicians PAC", amount: "$2.1M", partyLean: "D" },
      { name: "American Osteopathic Association PAC", amount: "$1.6M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Richard Neal", party: "D", office: "U.S. House", totalReceived: "$820K" },
      { name: "Michael Burgess", party: "R", office: "U.S. House", totalReceived: "$760K" },
      { name: "Greg Walden", party: "R", office: "U.S. House", totalReceived: "$700K" },
      { name: "Frank Pallone", party: "D", office: "U.S. House", totalReceived: "$660K" },
      { name: "Chuck Grassley", party: "R", office: "U.S. Senate", totalReceived: "$580K" },
    ],
    interestBreakdown: [
      { label: "Medicare Physician Payment (SGR)", pct: 34 },
      { label: "Scope of Practice Laws", pct: 22 },
      { label: "Health Insurance Market Rules", pct: 20 },
      { label: "Malpractice & Tort Reform", pct: 14 },
      { label: "Medical Education & Residencies", pct: 10 },
    ],
  },
  {
    name: "American Petroleum Institute",
    tag: "API",
    acronym: "API",
    description: "The American Petroleum Institute is the primary trade association for the oil and gas industry, spending $60–$90M annually to protect fossil fuel subsidies, oppose carbon taxes and emissions standards, and block clean energy mandates. API funded decades of climate-change denial and continues to lobby against EPA regulations on methane, vehicle emissions, and offshore drilling rules. The industry it represents receives approximately $20B per year in federal subsidies.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$60M–$90M",
    partySplitDem: 14,
    partySplitRep: 86,
    website: "https://www.api.org",
    headquarters: "Washington, DC",
    industry: "oil_gas",
    influenceScore: -45,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=E01",
    topPacs: [
      { name: "Koch Industries PAC", amount: "$9.4M", partyLean: "R" },
      { name: "ExxonMobil Corp PAC", amount: "$6.0M", partyLean: "R" },
      { name: "Chevron Corp PAC", amount: "$5.2M", partyLean: "R" },
      { name: "American Petroleum Institute (direct)", amount: "$66.0M", partyLean: "R" },
      { name: "ConocoPhillips PAC", amount: "$3.8M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "John Cornyn", party: "R", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Ted Cruz", party: "R", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Kevin Cramer", party: "R", office: "U.S. Senate", totalReceived: "$1.0M" },
      { name: "John Barrasso", party: "R", office: "U.S. Senate", totalReceived: "$940K" },
      { name: "Steve Scalise", party: "R", office: "U.S. House", totalReceived: "$860K" },
    ],
    interestBreakdown: [
      { label: "Fossil Fuel Subsidies Defense", pct: 28 },
      { label: "EPA Emissions Rules Opposition", pct: 26 },
      { label: "Offshore & Federal Lands Drilling", pct: 18 },
      { label: "Pipeline Permitting", pct: 16 },
      { label: "Carbon Tax Opposition", pct: 12 },
    ],
  },
  {
    name: "National Education Association",
    tag: "NEA",
    acronym: "NEA",
    description: "The National Education Association is the largest labor union and professional association in the U.S., representing 3 million public school educators and spending $30–$50M per election cycle. It is the largest single donor to Democratic campaigns among all unions and advocacy groups. The NEA lobbies for increased public school funding, opposes school vouchers and charter school expansion, and fights for teacher pension protections.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$30M–$50M",
    partySplitDem: 94,
    partySplitRep: 6,
    website: "https://www.nea.org",
    headquarters: "Washington, DC",
    industry: "education",
    influenceScore: 28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/national-education-assn/summary?id=d000000064",
    topPacs: [
      { name: "NEA Fund for Children & Public Education", amount: "$38.2M", partyLean: "D" },
      { name: "NEA Advocacy Fund", amount: "$8.6M", partyLean: "D" },
      { name: "State affiliate PACs (combined)", amount: "$12.0M", partyLean: "D" },
      { name: "National Board for Professional Teaching PAC", amount: "$1.4M", partyLean: "D" },
      { name: "Alliance for Quality Education", amount: "$1.0M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.4M" },
      { name: "Patty Murray", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Bernie Sanders", party: "D", office: "U.S. Senate", totalReceived: "$980K" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$860K" },
      { name: "Mark Kelly", party: "D", office: "U.S. Senate", totalReceived: "$780K" },
    ],
    interestBreakdown: [
      { label: "Public School Funding (Title I)", pct: 30 },
      { label: "Voucher & Charter School Opposition", pct: 26 },
      { label: "Teacher Pay & Pension", pct: 22 },
      { label: "Student Loan Debt Relief", pct: 12 },
      { label: "Standardized Testing & Accountability", pct: 10 },
    ],
  },
  {
    name: "National Defense Industrial Association",
    tag: "NDIA",
    acronym: "NDIA",
    description: "The National Defense Industrial Association represents over 1,700 defense contractors and is the chief advocate for maintaining and increasing the Pentagon's $800B+ annual budget. Member companies — including Lockheed Martin, Raytheon, Boeing, and Northrop Grumman — spend $120–$200M annually combined on lobbying. The defense-industrial complex enjoys broad bipartisan support as major contractors deliberately spread production facilities across nearly every congressional district.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$120M–$200M",
    partySplitDem: 46,
    partySplitRep: 54,
    website: "https://www.ndia.org",
    headquarters: "Arlington, VA",
    industry: "defense",
    influenceScore: -28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=D",
    topPacs: [
      { name: "Lockheed Martin PAC", amount: "$5.8M", partyLean: "Split" },
      { name: "Raytheon Technologies PAC", amount: "$5.4M", partyLean: "Split" },
      { name: "Boeing Co PAC", amount: "$4.9M", partyLean: "Split" },
      { name: "Northrop Grumman PAC", amount: "$4.5M", partyLean: "Split" },
      { name: "General Dynamics PAC", amount: "$4.0M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Jack Reed", party: "D", office: "U.S. Senate", totalReceived: "$960K" },
      { name: "James Inhofe", party: "R", office: "U.S. Senate", totalReceived: "$900K" },
      { name: "Adam Smith", party: "D", office: "U.S. House", totalReceived: "$820K" },
      { name: "Mike Turner", party: "R", office: "U.S. House", totalReceived: "$740K" },
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$680K" },
    ],
    interestBreakdown: [
      { label: "Weapons Systems Procurement", pct: 35 },
      { label: "Pentagon Budget Increases", pct: 25 },
      { label: "Arms Export Controls", pct: 18 },
      { label: "Space & Cyber Programs", pct: 12 },
      { label: "R&D Contracts", pct: 10 },
    ],
  },
  {
    name: "America's Health Insurance Plans",
    tag: "AHIP",
    acronym: "AHIP",
    description: "America's Health Insurance Plans (AHIP) is the chief trade association for the private health insurance industry, representing companies that collectively earn over $1 trillion in annual revenue. It spends $100–$150M annually opposing a public health insurance option, Medicare for All, and government-set rate caps. AHIP spent $86M to defeat the public option in the Affordable Care Act negotiations and has continued to fight any reform that would reduce private insurers' market dominance.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$100M–$150M",
    partySplitDem: 46,
    partySplitRep: 54,
    website: "https://www.ahip.org",
    headquarters: "Washington, DC",
    industry: "insurance",
    influenceScore: -30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=F09",
    topPacs: [
      { name: "UnitedHealth Group PAC", amount: "$5.9M", partyLean: "Split" },
      { name: "Blue Cross/Blue Shield PAC", amount: "$5.4M", partyLean: "D" },
      { name: "Cigna Corp PAC", amount: "$4.2M", partyLean: "Split" },
      { name: "Aetna Inc (CVS Health) PAC", amount: "$4.0M", partyLean: "Split" },
      { name: "Humana Inc PAC", amount: "$3.4M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Kevin McCarthy", party: "R", office: "U.S. House", totalReceived: "$940K" },
      { name: "Richard Neal", party: "D", office: "U.S. House", totalReceived: "$880K" },
      { name: "Cathy McMorris Rodgers", party: "R", office: "U.S. House", totalReceived: "$720K" },
      { name: "Mike Crapo", party: "R", office: "U.S. Senate", totalReceived: "$660K" },
      { name: "Steny Hoyer", party: "D", office: "U.S. House", totalReceived: "$620K" },
    ],
    interestBreakdown: [
      { label: "Public Option & Medicare for All Opposition", pct: 38 },
      { label: "ACA Market Rules & Subsidies", pct: 22 },
      { label: "Medicaid Managed Care", pct: 18 },
      { label: "Medicare Advantage Rates", pct: 14 },
      { label: "Drug Cost Transparency", pct: 8 },
    ],
  },
  {
    name: "American Bankers Association",
    tag: "ABA",
    acronym: "ABA",
    description: "The American Bankers Association represents large and mid-sized banks and spends $20–$40M annually lobbying against consumer financial protections, CFPB enforcement authority, and post-2008 banking regulations. Along with the broader financial sector, ABA was instrumental in rolling back key provisions of Dodd-Frank and continues to fight payday loan rules, overdraft fee caps, and data privacy requirements that would benefit consumers at banks' expense.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$20M–$40M",
    partySplitDem: 40,
    partySplitRep: 60,
    website: "https://www.aba.com",
    headquarters: "Washington, DC",
    industry: "banking",
    influenceScore: -28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-bankers-assn/summary?id=d000000116",
    topPacs: [
      { name: "ABA BankPac", amount: "$6.8M", partyLean: "Split" },
      { name: "JPMorgan Chase PAC", amount: "$5.2M", partyLean: "Split" },
      { name: "Bank of America PAC", amount: "$4.4M", partyLean: "Split" },
      { name: "Wells Fargo PAC", amount: "$4.0M", partyLean: "Split" },
      { name: "Citigroup Inc PAC", amount: "$3.6M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Sherrod Brown", party: "D", office: "U.S. Senate", totalReceived: "$920K" },
      { name: "Pat Toomey", party: "R", office: "U.S. Senate", totalReceived: "$880K" },
      { name: "Mike Crapo", party: "R", office: "U.S. Senate", totalReceived: "$820K" },
      { name: "Tim Scott", party: "R", office: "U.S. Senate", totalReceived: "$760K" },
      { name: "Chuck Schumer", party: "D", office: "U.S. Senate", totalReceived: "$720K" },
    ],
    interestBreakdown: [
      { label: "CFPB Authority & Enforcement", pct: 30 },
      { label: "Dodd-Frank Rollback", pct: 24 },
      { label: "Overdraft & Fee Rules", pct: 20 },
      { label: "Capital Requirements", pct: 16 },
      { label: "Crypto & Fintech Regulation", pct: 10 },
    ],
  },
  {
    name: "Service Employees International Union",
    tag: "SEIU",
    acronym: "SEIU",
    description: "The SEIU represents 2 million workers in healthcare, property services, and public employment — disproportionately low-wage workers, women, and workers of color. It is one of the most effective political spenders in the labor movement, contributing $50–$80M per cycle almost entirely to Democrats. The SEIU was the driving force behind the Fight for $15 minimum wage campaign, which has resulted in $15+ minimum wages in over 30 states and cities.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$50M–$80M",
    partySplitDem: 96,
    partySplitRep: 4,
    website: "https://www.seiu.org",
    headquarters: "Washington, DC",
    industry: "labor",
    influenceScore: 38,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/service-employees-international-union/summary?id=d000000581",
    topPacs: [
      { name: "SEIU Political Education & Action Fund", amount: "$38.4M", partyLean: "D" },
      { name: "SEIU Committee on Political Education (COPE)", amount: "$14.8M", partyLean: "D" },
      { name: "SEIU Healthcare Workers PAC", amount: "$6.2M", partyLean: "D" },
      { name: "SEIU 1199 (NY healthcare) PAC", amount: "$5.0M", partyLean: "D" },
      { name: "SEIU Local 32BJ PAC", amount: "$3.4M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$3.2M" },
      { name: "Hillary Clinton", party: "D", office: "President", totalReceived: "$2.4M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Sherrod Brown", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "John Fetterman", party: "D", office: "U.S. Senate", totalReceived: "$1.0M" },
    ],
    interestBreakdown: [
      { label: "$15 Minimum Wage & Living Wage", pct: 32 },
      { label: "Healthcare Worker Staffing Ratios", pct: 24 },
      { label: "PRO Act & Union Organizing Rights", pct: 22 },
      { label: "Immigrant Worker Protections", pct: 12 },
      { label: "Home Care & Medicaid Funding", pct: 10 },
    ],
  },
  {
    name: "Sierra Club",
    tag: "SIERRA_CLUB",
    acronym: "Sierra Club",
    description: "Founded in 1892, the Sierra Club is America's oldest and largest environmental organization with 3.5 million members. Its political arm spends $20–$40M per cycle opposing fossil fuel expansion, supporting clean energy legislation, and electing pro-environment candidates. The Sierra Club's Beyond Coal campaign contributed to the closure of over 300 coal plants and it was a key advocate for the Inflation Reduction Act's clean energy investments.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$40M",
    partySplitDem: 95,
    partySplitRep: 5,
    website: "https://www.sierraclub.org",
    headquarters: "Oakland, CA",
    industry: "environment",
    influenceScore: 40,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/sierra-club/summary?id=d000000049",
    topPacs: [
      { name: "Sierra Club Political Committee", amount: "$22.4M", partyLean: "D" },
      { name: "Sierra Club Foundation (advocacy)", amount: "$8.6M", partyLean: "D" },
      { name: "League of Conservation Voters PAC", amount: "$18.0M", partyLean: "D" },
      { name: "Environment America PAC", amount: "$2.4M", partyLean: "D" },
      { name: "350 Action Fund", amount: "$1.8M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.1M" },
      { name: "Mark Kelly", party: "D", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "John Ossoff", party: "D", office: "U.S. Senate", totalReceived: "$1.0M" },
      { name: "Catherine Cortez Masto", party: "D", office: "U.S. Senate", totalReceived: "$880K" },
    ],
    interestBreakdown: [
      { label: "Climate & Clean Energy Legislation", pct: 34 },
      { label: "Beyond Coal / Fossil Fuel Phase-Out", pct: 26 },
      { label: "Public Lands & National Parks", pct: 18 },
      { label: "Clean Air & Water Rules", pct: 14 },
      { label: "Environmental Justice", pct: 8 },
    ],
  },
  {
    name: "American Farm Bureau Federation",
    tag: "AFBF",
    acronym: "AFBF",
    description: "The American Farm Bureau Federation is the largest farm organization in the U.S., representing 6 million member families and spending $20–$40M annually. It lobbies for large farm subsidies, crop insurance programs, trade protections, and against environmental regulations on pesticides and water quality. The AFBF primarily represents large industrial agribusiness interests rather than small family farmers and is closely aligned with the Republican Party.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$20M–$40M",
    partySplitDem: 30,
    partySplitRep: 70,
    website: "https://www.fb.org",
    headquarters: "Washington, DC",
    industry: "agriculture",
    influenceScore: -10,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-farm-bureau/summary?id=d000000070",
    topPacs: [
      { name: "American Farm Bureau PAC", amount: "$6.2M", partyLean: "R" },
      { name: "Archer-Daniels-Midland PAC", amount: "$3.9M", partyLean: "Split" },
      { name: "National Corn Growers Assn PAC", amount: "$2.8M", partyLean: "R" },
      { name: "American Soybean Assn PAC", amount: "$2.2M", partyLean: "R" },
      { name: "Cargill Inc PAC", amount: "$2.0M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$900K" },
      { name: "Chuck Grassley", party: "R", office: "U.S. Senate", totalReceived: "$820K" },
      { name: "Debbie Stabenow", party: "D", office: "U.S. Senate", totalReceived: "$760K" },
      { name: "John Boozman", party: "R", office: "U.S. Senate", totalReceived: "$680K" },
      { name: "Joni Ernst", party: "R", office: "U.S. Senate", totalReceived: "$620K" },
    ],
    interestBreakdown: [
      { label: "Farm Bill Subsidies & Crop Insurance", pct: 34 },
      { label: "Pesticide & GMO Regulations", pct: 22 },
      { label: "Trade & Export Policy", pct: 20 },
      { label: "Waters of the U.S. (WOTUS) Rules", pct: 14 },
      { label: "Farmworker Immigration Policy", pct: 10 },
    ],
  },
  {
    name: "Fraternal Order of Police",
    tag: "FOP",
    acronym: "FOP",
    description: "The Fraternal Order of Police is the world's largest law enforcement organization, representing over 360,000 sworn officers. It spends $3–$10M annually lobbying against police accountability legislation, opposing qualified immunity reform, and fighting civilian oversight proposals. The FOP endorsed Donald Trump in 2016 and 2020 and has become one of the most visible opponents of the George Floyd Justice in Policing Act.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$3M–$10M",
    partySplitDem: 20,
    partySplitRep: 80,
    website: "https://www.fop.net",
    headquarters: "Nashville, TN",
    industry: "law_enforcement",
    influenceScore: -18,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/fraternal-order-of-police/summary?id=d000021714",
    topPacs: [
      { name: "FOP National PAC", amount: "$4.8M", partyLean: "R" },
      { name: "National Association of Police Organizations PAC", amount: "$2.4M", partyLean: "R" },
      { name: "International Assn of Chiefs of Police PAC", amount: "$1.4M", partyLean: "R" },
      { name: "Police Benevolent Assn PAC (NY)", amount: "$1.2M", partyLean: "R" },
      { name: "Law Enforcement Alliance of America", amount: "$0.8M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", office: "President", totalReceived: "$1.6M" },
      { name: "Tom Cotton", party: "R", office: "U.S. Senate", totalReceived: "$640K" },
      { name: "John Cornyn", party: "R", office: "U.S. Senate", totalReceived: "$580K" },
      { name: "Steve Scalise", party: "R", office: "U.S. House", totalReceived: "$480K" },
      { name: "Kevin McCarthy", party: "R", office: "U.S. House", totalReceived: "$420K" },
    ],
    interestBreakdown: [
      { label: "Qualified Immunity Protection", pct: 30 },
      { label: "Police Funding & Hiring", pct: 26 },
      { label: "Anti-Defunding Opposition", pct: 24 },
      { label: "Officer Due Process Rights", pct: 12 },
      { label: "Use-of-Force Policy", pct: 8 },
    ],
  },
  {
    name: "American Federation of State, County & Municipal Employees",
    tag: "AFSCME",
    acronym: "AFSCME",
    description: "AFSCME represents 1.4 million public-sector workers — nurses, corrections officers, sanitation workers, and child care providers — making it one of the largest public employee unions in the world. It spends $40–$60M per cycle almost entirely backing Democrats, focusing on defending collective bargaining rights for government workers and opposing public service privatization. AFSCME fought a landmark Supreme Court battle (Janus v. AFSCME) over public-sector union fees.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$40M–$60M",
    partySplitDem: 94,
    partySplitRep: 6,
    website: "https://www.afscme.org",
    headquarters: "Washington, DC",
    industry: "government_workers",
    influenceScore: 32,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/afscme/summary?id=d000000061",
    topPacs: [
      { name: "AFSCME People PAC", amount: "$28.4M", partyLean: "D" },
      { name: "AFSCME PEOPLE (Separate Segregated Fund)", amount: "$14.2M", partyLean: "D" },
      { name: "AFSCME 1199 Political Contributions", amount: "$4.8M", partyLean: "D" },
      { name: "AFSCME Corrections Officers PAC", amount: "$2.4M", partyLean: "D" },
      { name: "American Nurses Assn PAC", amount: "$1.8M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.6M" },
      { name: "Hillary Clinton", party: "D", office: "President", totalReceived: "$2.1M" },
      { name: "Sherrod Brown", party: "D", office: "U.S. Senate", totalReceived: "$1.3M" },
      { name: "Patty Murray", party: "D", office: "U.S. Senate", totalReceived: "$1.1M" },
      { name: "Dick Durbin", party: "D", office: "U.S. Senate", totalReceived: "$940K" },
    ],
    interestBreakdown: [
      { label: "Public-Sector Collective Bargaining", pct: 34 },
      { label: "Privatization Opposition", pct: 24 },
      { label: "Public Pension Defense", pct: 20 },
      { label: "Minimum Wage & Benefits", pct: 14 },
      { label: "Healthcare Worker Safety", pct: 8 },
    ],
  },
  {
    name: "EMILY's List",
    tag: "EMILYS_LIST",
    acronym: "EMILY's List",
    description: "EMILY's List (Early Money Is Like Yeast) is the nation's largest resource for Democratic pro-choice women candidates, having helped elect over 1,000 women to office since its 1985 founding. It raised over $750M in the 2022 cycle alone, making it one of the most powerful single-issue PACs in American politics. The organization supports abortion rights, paid family leave, and gender pay equity alongside its primary mission of electing women to all levels of government.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$60M–$150M",
    partySplitDem: 100,
    partySplitRep: 0,
    website: "https://www.emilyslist.org",
    headquarters: "Washington, DC",
    industry: "womens_candidates",
    influenceScore: 30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/emilys-list/summary?id=d000000113",
    topPacs: [
      { name: "EMILY's List PAC", amount: "$84.0M", partyLean: "D" },
      { name: "EMILY's List Super PAC", amount: "$42.0M", partyLean: "D" },
      { name: "Women Vote! (EMILY's List IE fund)", amount: "$28.0M", partyLean: "D" },
      { name: "Planned Parenthood Action Fund PAC", amount: "$24.0M", partyLean: "D" },
      { name: "NARAL Pro-Choice America PAC", amount: "$6.4M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Hillary Clinton", party: "D", office: "President", totalReceived: "$24.0M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$8.4M" },
      { name: "Maggie Hassan", party: "D", office: "U.S. Senate", totalReceived: "$6.2M" },
      { name: "Catherine Cortez Masto", party: "D", office: "U.S. Senate", totalReceived: "$5.8M" },
      { name: "Stacey Abrams", party: "D", office: "Governor", totalReceived: "$4.4M" },
    ],
    interestBreakdown: [
      { label: "Women Candidate Recruitment & Funding", pct: 38 },
      { label: "Reproductive Rights & Abortion Access", pct: 28 },
      { label: "Paid Family & Medical Leave", pct: 16 },
      { label: "Equal Pay & Gender Equity", pct: 12 },
      { label: "Childcare & Early Education", pct: 6 },
    ],
  },
  {
    name: "Human Rights Campaign",
    tag: "HRC",
    acronym: "HRC",
    description: "The Human Rights Campaign is the largest LGBTQ+ civil rights organization in the U.S., with over 3 million members and spending $10–$25M per cycle on political activity. It played a central role in securing marriage equality, repealing Don't Ask Don't Tell, and advancing non-discrimination protections. The HRC's Corporate Equality Index drives major corporations to adopt LGBTQ+ inclusive policies as a condition of their public reputation.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$10M–$25M",
    partySplitDem: 98,
    partySplitRep: 2,
    website: "https://www.hrc.org",
    headquarters: "Washington, DC",
    industry: "civil_rights",
    influenceScore: 42,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/human-rights-campaign/summary?id=d000000158",
    topPacs: [
      { name: "HRC PAC", amount: "$12.4M", partyLean: "D" },
      { name: "HRC Equality Votes (Super PAC)", amount: "$8.6M", partyLean: "D" },
      { name: "Victory Fund & Institute PAC", amount: "$4.2M", partyLean: "D" },
      { name: "GLBTQ Legal Advocates & Defenders Action Fund", amount: "$1.8M", partyLean: "D" },
      { name: "National Center for Transgender Equality PAC", amount: "$1.2M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$1.8M" },
      { name: "Mark Kelly", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$1.1M" },
      { name: "Tammy Baldwin", party: "D", office: "U.S. Senate", totalReceived: "$980K" },
      { name: "John Ossoff", party: "D", office: "U.S. Senate", totalReceived: "$880K" },
    ],
    interestBreakdown: [
      { label: "Non-Discrimination Protections (LGBTQ+)", pct: 32 },
      { label: "Marriage Equality Defense", pct: 24 },
      { label: "Transgender Rights & Healthcare", pct: 22 },
      { label: "Don't Ask Don't Tell Repeal Legacy", pct: 12 },
      { label: "HIV/AIDS Funding", pct: 10 },
    ],
  },
  {
    name: "Planned Parenthood Action Fund",
    tag: "PPAF",
    acronym: "PPAF",
    description: "Planned Parenthood Action Fund is the political arm of Planned Parenthood Federation of America, which provides reproductive health services to over 2.4 million patients annually. The Action Fund spends $20–$45M per cycle to elect pro-choice candidates and defeat efforts to defund Planned Parenthood. It has been the primary target of the anti-abortion movement's political strategy since the 1980s and faced continued defunding attempts following the Dobbs decision in 2022.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$45M",
    partySplitDem: 99,
    partySplitRep: 1,
    website: "https://www.plannedparenthoodaction.org",
    headquarters: "New York, NY",
    industry: "reproductive_rights",
    influenceScore: 38,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/planned-parenthood/summary?id=d000000591",
    topPacs: [
      { name: "Planned Parenthood Votes PAC (Super PAC)", amount: "$28.0M", partyLean: "D" },
      { name: "Planned Parenthood Action Fund Inc PAC", amount: "$8.4M", partyLean: "D" },
      { name: "NARAL Pro-Choice America PAC", amount: "$6.4M", partyLean: "D" },
      { name: "Center for Reproductive Rights Action Fund", amount: "$3.2M", partyLean: "D" },
      { name: "All Above All Action Fund", amount: "$1.4M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.4M" },
      { name: "Hillary Clinton", party: "D", office: "President", totalReceived: "$2.0M" },
      { name: "Mark Kelly", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$1.0M" },
      { name: "Catherine Cortez Masto", party: "D", office: "U.S. Senate", totalReceived: "$880K" },
    ],
    interestBreakdown: [
      { label: "Abortion Access & Funding Defense", pct: 40 },
      { label: "Contraception & Family Planning", pct: 24 },
      { label: "Title X Family Planning Funding", pct: 18 },
      { label: "Defunding Opposition", pct: 12 },
      { label: "STI Testing & Treatment", pct: 6 },
    ],
  },
  {
    name: "National Right to Life Committee",
    tag: "NRLC",
    acronym: "NRLC",
    description: "The National Right to Life Committee is the oldest and largest anti-abortion organization in the U.S., founded in 1968 and spending $4–$15M per cycle through its political action arm. It supports constitutional abortion bans, opposes embryonic stem cell research, and fights euthanasia legislation. The NRLC's lobbying helped draft model state legislation adopted across dozens of states and it played a key advisory role in the Dobbs v. Jackson Women's Health Organization litigation strategy.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$4M–$15M",
    partySplitDem: 2,
    partySplitRep: 98,
    website: "https://www.nrlc.org",
    headquarters: "Washington, DC",
    industry: "pro_life",
    influenceScore: -20,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/national-right-to-life-cmte/summary?id=d000000066",
    topPacs: [
      { name: "National Right to Life PAC", amount: "$4.8M", partyLean: "R" },
      { name: "Susan B. Anthony Pro-Life America PAC", amount: "$8.2M", partyLean: "R" },
      { name: "Live Action PAC", amount: "$2.4M", partyLean: "R" },
      { name: "March for Life Action PAC", amount: "$1.6M", partyLean: "R" },
      { name: "Americans United for Life PAC", amount: "$1.2M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", office: "President", totalReceived: "$1.4M" },
      { name: "Tom Cotton", party: "R", office: "U.S. Senate", totalReceived: "$820K" },
      { name: "Mike Pence", party: "R", office: "Vice President", totalReceived: "$740K" },
      { name: "Marco Rubio", party: "R", office: "U.S. Senate", totalReceived: "$680K" },
      { name: "Ted Cruz", party: "R", office: "U.S. Senate", totalReceived: "$620K" },
    ],
    interestBreakdown: [
      { label: "Federal & State Abortion Bans", pct: 40 },
      { label: "Embryonic Stem Cell Research Opposition", pct: 20 },
      { label: "Late-Term Abortion Restrictions", pct: 18 },
      { label: "Euthanasia & End-of-Life Policy", pct: 14 },
      { label: "Judicial Nominations (anti-abortion)", pct: 8 },
    ],
  },
  {
    name: "Family Research Council",
    tag: "FRC",
    acronym: "FRC",
    description: "The Family Research Council is the leading religious-conservative advocacy organization in Washington, designated a hate group by the Southern Poverty Law Center for its anti-LGBTQ+ positions. Spending $5–$15M annually, it lobbies for school prayer, against LGBTQ+ non-discrimination laws, against reproductive rights, and for embedding evangelical Christian policy positions into federal law. FRC's annual Values Voter Summit is a required stop for Republican presidential candidates.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$5M–$15M",
    partySplitDem: 1,
    partySplitRep: 99,
    website: "https://www.frc.org",
    headquarters: "Washington, DC",
    industry: "religious_conservative",
    influenceScore: -22,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/family-research-council/summary?id=d000026842",
    topPacs: [
      { name: "FRC Action PAC", amount: "$4.2M", partyLean: "R" },
      { name: "Focus on the Family Action PAC", amount: "$3.6M", partyLean: "R" },
      { name: "American Family Association PAC", amount: "$2.8M", partyLean: "R" },
      { name: "Traditional Values Coalition PAC", amount: "$1.6M", partyLean: "R" },
      { name: "Liberty Counsel Action PAC", amount: "$1.2M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", office: "President", totalReceived: "$1.2M" },
      { name: "Mike Pence", party: "R", office: "Vice President", totalReceived: "$860K" },
      { name: "Ted Cruz", party: "R", office: "U.S. Senate", totalReceived: "$720K" },
      { name: "Marco Rubio", party: "R", office: "U.S. Senate", totalReceived: "$640K" },
      { name: "Ralph Norman", party: "R", office: "U.S. House", totalReceived: "$480K" },
    ],
    interestBreakdown: [
      { label: "Anti-LGBTQ+ Policy & Religious Liberty", pct: 34 },
      { label: "Abortion & Contraception Opposition", pct: 26 },
      { label: "School Prayer & Religious Education", pct: 18 },
      { label: "Judicial Nominations (social conservative)", pct: 14 },
      { label: "Marriage Definition Laws", pct: 8 },
    ],
  },
  {
    name: "Heritage Action for America",
    tag: "HERITAGE_ACTION",
    acronym: "Heritage Action",
    description: "Heritage Action for America is the advocacy arm of the Heritage Foundation, the most influential conservative think tank in Washington. It spends $5–$20M annually promoting free-market, limited-government conservatism through its legislative scorecard that primary challengers use to threaten incumbent Republicans. Heritage Action's Project 2025 blueprint became the centerpiece of conservative policy planning for a potential second Trump term.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$5M–$20M",
    partySplitDem: 0,
    partySplitRep: 100,
    website: "https://www.heritageaction.com",
    headquarters: "Washington, DC",
    industry: "conservative_policy",
    influenceScore: -30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/heritage-action-for-america/summary?id=d000048863",
    topPacs: [
      { name: "Heritage Action for America PAC", amount: "$8.4M", partyLean: "R" },
      { name: "Club for Growth Action PAC", amount: "$28.0M", partyLean: "R" },
      { name: "FreedomWorks PAC", amount: "$6.4M", partyLean: "R" },
      { name: "Heritage Foundation (education/lobbying)", amount: "$12.0M", partyLean: "R" },
      { name: "Cato Action Fund", amount: "$2.8M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", office: "President", totalReceived: "$2.1M" },
      { name: "Ted Cruz", party: "R", office: "U.S. Senate", totalReceived: "$1.6M" },
      { name: "Rand Paul", party: "R", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Matt Gaetz", party: "R", office: "U.S. House", totalReceived: "$980K" },
      { name: "Jim Jordan", party: "R", office: "U.S. House", totalReceived: "$860K" },
    ],
    interestBreakdown: [
      { label: "Deregulation & Small Government", pct: 28 },
      { label: "Conservative Judicial Nominations", pct: 24 },
      { label: "Tax Cuts & Spending Reductions", pct: 22 },
      { label: "Immigration Restriction", pct: 16 },
      { label: "School Choice & Anti-DEI Policy", pct: 10 },
    ],
  },
  {
    name: "American Civil Liberties Union",
    tag: "ACLU",
    acronym: "ACLU",
    description: "The ACLU is America's leading civil liberties organization, founded in 1920 and now spending $20–$50M per cycle through its political arm defending constitutional rights. It litigates and lobbies on free speech, privacy, voting rights, criminal justice reform, immigration, and reproductive rights. The ACLU mobilized its largest-ever donation surge of $24M in 36 hours following the 2017 travel ban, cementing its role as a major resistance-era political organization.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$50M",
    partySplitDem: 90,
    partySplitRep: 10,
    website: "https://www.aclu.org",
    headquarters: "New York, NY",
    industry: "civil_liberties",
    influenceScore: 42,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-civil-liberties-union/summary?id=d000024778",
    topPacs: [
      { name: "ACLU Voter Education Project", amount: "$14.0M", partyLean: "D" },
      { name: "ACLU People Power (grassroots)", amount: "$8.4M", partyLean: "D" },
      { name: "National Immigration Law Center Action PAC", amount: "$2.4M", partyLean: "D" },
      { name: "Lawyers Committee for Civil Rights PAC", amount: "$1.8M", partyLean: "D" },
      { name: "Electronic Frontier Foundation Action", amount: "$1.4M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$1.6M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Mark Kelly", party: "D", office: "U.S. Senate", totalReceived: "$1.0M" },
      { name: "Stacey Abrams", party: "D", office: "Governor", totalReceived: "$880K" },
      { name: "Ron Wyden", party: "D", office: "U.S. Senate", totalReceived: "$780K" },
    ],
    interestBreakdown: [
      { label: "Voting Rights & Election Access", pct: 28 },
      { label: "Criminal Justice Reform & Policing", pct: 24 },
      { label: "Privacy & Surveillance", pct: 20 },
      { label: "Reproductive & LGBTQ+ Rights", pct: 16 },
      { label: "Immigration & Refugee Rights", pct: 12 },
    ],
  },
  {
    name: "Americans for Prosperity",
    tag: "AMERICANS_FOR_PROSPERITY",
    acronym: "AFP",
    description: "Americans for Prosperity is the flagship political organization of the Koch network, funded by Charles Koch and allied billionaires to advance free-market, anti-regulation policy. It spends $80–$150M per cycle through AFP and its sister organizations, making it one of the largest outside political spenders. AFP has been the primary funder of climate-change denial campaigns, opposition to the Affordable Care Act, and lobbying against minimum wage increases.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$80M–$150M",
    partySplitDem: 2,
    partySplitRep: 98,
    website: "https://americansforprosperity.org",
    headquarters: "Arlington, VA",
    industry: "libertarian",
    influenceScore: -38,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/americans-for-prosperity/summary?id=d000031473",
    topPacs: [
      { name: "Americans for Prosperity Action PAC", amount: "$64.0M", partyLean: "R" },
      { name: "Koch Industries PAC", amount: "$9.6M", partyLean: "R" },
      { name: "Freedom Partners Chamber of Commerce", amount: "$28.0M", partyLean: "R" },
      { name: "AFP Foundation (issue advocacy)", amount: "$22.0M", partyLean: "R" },
      { name: "Stand Together PAC (Koch network)", amount: "$38.0M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$2.8M" },
      { name: "Marco Rubio", party: "R", office: "U.S. Senate", totalReceived: "$2.2M" },
      { name: "Ted Cruz", party: "R", office: "U.S. Senate", totalReceived: "$2.0M" },
      { name: "Scott Walker", party: "R", office: "Governor", totalReceived: "$1.8M" },
      { name: "Pat Toomey", party: "R", office: "U.S. Senate", totalReceived: "$1.6M" },
    ],
    interestBreakdown: [
      { label: "ACA Repeal & Healthcare Deregulation", pct: 28 },
      { label: "Climate Policy Opposition", pct: 26 },
      { label: "Anti-Union Legislation", pct: 20 },
      { label: "Tax Cuts & Fiscal Austerity", pct: 16 },
      { label: "School Choice & Anti-Regulation", pct: 10 },
    ],
  },
  {
    name: "MoveOn",
    tag: "MOVEON",
    acronym: "MoveOn",
    description: "MoveOn is one of the largest progressive grassroots organizations in the U.S., with over 10 million members and spending $30–$60M per cycle on digital organizing, candidate support, and issue campaigns. Founded in 1998 to oppose the Clinton impeachment, it grew into a major force driving anti-Iraq War activism, Bernie Sanders' 2016 campaign, and the 2018 Democratic wave. MoveOn prioritizes Medicare for All, Green New Deal, and democracy reform.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$30M–$60M",
    partySplitDem: 100,
    partySplitRep: 0,
    website: "https://www.moveon.org",
    headquarters: "Washington, DC",
    industry: "progressive",
    influenceScore: 35,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/moveonorg/summary?id=d000021585",
    topPacs: [
      { name: "MoveOn.org Civic Action (c4)", amount: "$22.0M", partyLean: "D" },
      { name: "MoveOn.org Political Action PAC", amount: "$14.4M", partyLean: "D" },
      { name: "Progressive Change Campaign Committee PAC", amount: "$4.8M", partyLean: "D" },
      { name: "Democracy for America PAC", amount: "$3.6M", partyLean: "D" },
      { name: "Our Revolution PAC (Sanders-linked)", amount: "$6.2M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Bernie Sanders", party: "D", office: "U.S. Senate / President", totalReceived: "$4.8M" },
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$3.2M" },
      { name: "Alexandra Ocasio-Cortez", party: "D", office: "U.S. House", totalReceived: "$1.8M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Mark Kelly", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
    ],
    interestBreakdown: [
      { label: "Medicare for All & Healthcare", pct: 28 },
      { label: "Green New Deal & Climate", pct: 26 },
      { label: "Democracy Reform & Voting Rights", pct: 22 },
      { label: "Anti-War & Foreign Policy", pct: 14 },
      { label: "Economic Inequality & Taxes", pct: 10 },
    ],
  },
  {
    name: "Altria Group (Philip Morris USA)",
    tag: "ALTRIA",
    acronym: "Altria",
    description: "Altria Group, the parent company of Philip Morris USA, is the dominant U.S. tobacco company and one of Washington's most durable corporate lobbies, spending $10–$20M annually. It has fought FDA tobacco regulation, graphic health warnings, menthol cigarette bans, and nicotine reduction mandates for decades. Despite the decline of cigarette smoking, Altria maintains significant political influence through its vast lobbying infrastructure and cross-party campaign giving.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$10M–$20M",
    partySplitDem: 35,
    partySplitRep: 65,
    website: "https://www.altria.com",
    headquarters: "Richmond, VA",
    industry: "tobacco",
    influenceScore: -32,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/altria-group/summary?id=d000000022",
    topPacs: [
      { name: "Altria Group / Philip Morris USA PAC", amount: "$4.8M", partyLean: "Split" },
      { name: "Reynolds American (R.J. Reynolds) PAC", amount: "$3.2M", partyLean: "R" },
      { name: "Lorillard Inc PAC", amount: "$1.6M", partyLean: "R" },
      { name: "Swisher International PAC", amount: "$0.9M", partyLean: "R" },
      { name: "National Tobacco Industry PAC (combined)", amount: "$2.2M", partyLean: "R" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$640K" },
      { name: "Roy Blunt", party: "R", office: "U.S. Senate", totalReceived: "$580K" },
      { name: "Richard Burr", party: "R", office: "U.S. Senate", totalReceived: "$520K" },
      { name: "Thom Tillis", party: "R", office: "U.S. Senate", totalReceived: "$480K" },
      { name: "Greg Murphy", party: "R", office: "U.S. House", totalReceived: "$420K" },
    ],
    interestBreakdown: [
      { label: "FDA Tobacco Regulation Opposition", pct: 34 },
      { label: "Menthol Ban Opposition", pct: 24 },
      { label: "Nicotine Reduction Mandate Opposition", pct: 20 },
      { label: "Graphic Health Warning Litigation", pct: 14 },
      { label: "E-Cigarette & Vaping Policy", pct: 8 },
    ],
  },
  {
    name: "Airlines for America",
    tag: "A4A",
    acronym: "A4A",
    description: "Airlines for America is the principal trade organization for the U.S. airline industry, representing American Airlines, Delta, United, Southwest, and other major carriers. It spends $5–$15M annually lobbying against increased consumer protections, opposing slot controls at congested airports, pushing for government bailouts during crises (receiving $54B in Covid-19 relief), and resisting stricter safety regulations. The organization successfully lobbied against the DOT's proposed junk-fee disclosure rules.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$5M–$15M",
    partySplitDem: 42,
    partySplitRep: 58,
    website: "https://www.airlines.org",
    headquarters: "Washington, DC",
    industry: "aviation",
    influenceScore: -18,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/airlines-for-america/summary?id=d000021867",
    topPacs: [
      { name: "American Airlines Group PAC", amount: "$3.9M", partyLean: "Split" },
      { name: "Delta Air Lines PAC", amount: "$3.4M", partyLean: "Split" },
      { name: "United Airlines Holdings PAC", amount: "$3.1M", partyLean: "Split" },
      { name: "Southwest Airlines PAC", amount: "$2.6M", partyLean: "Split" },
      { name: "A4A Industry PAC (combined)", amount: "$2.0M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Sam Graves", party: "R", office: "U.S. House", totalReceived: "$820K" },
      { name: "Ted Cruz", party: "R", office: "U.S. Senate", totalReceived: "$740K" },
      { name: "Maria Cantwell", party: "D", office: "U.S. Senate", totalReceived: "$680K" },
      { name: "Roger Wicker", party: "R", office: "U.S. Senate", totalReceived: "$620K" },
      { name: "John Thune", party: "R", office: "U.S. Senate", totalReceived: "$580K" },
    ],
    interestBreakdown: [
      { label: "Consumer Protection Rule Opposition", pct: 28 },
      { label: "Covid-19 & Future Bailout Advocacy", pct: 24 },
      { label: "Airport Slot & Route Policy", pct: 22 },
      { label: "Safety Certification Lobbying", pct: 16 },
      { label: "Carbon & Emissions Policy", pct: 10 },
    ],
  },
  {
    name: "NetChoice",
    tag: "NETCHOICE",
    acronym: "NetChoice",
    description: "NetChoice is a trade association representing major internet platforms including Google, Meta, Amazon, TikTok, and Twitter/X. It spends $5–$15M annually litigating and lobbying against content moderation laws, state social media regulations, and antitrust enforcement against Big Tech. NetChoice won landmark First Amendment victories at the Supreme Court in 2024, shaping how governments can regulate online platforms' algorithmic curation and content decisions.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$5M–$15M",
    partySplitDem: 55,
    partySplitRep: 45,
    website: "https://netchoice.org",
    headquarters: "Washington, DC",
    industry: "technology",
    influenceScore: -12,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/netchoice/summary?id=d000067978",
    topPacs: [
      { name: "Meta Platforms PAC", amount: "$5.4M", partyLean: "D" },
      { name: "Google / Alphabet PAC", amount: "$6.0M", partyLean: "D" },
      { name: "Amazon.com Inc PAC", amount: "$6.6M", partyLean: "D" },
      { name: "NetChoice LLC (direct lobbying)", amount: "$8.4M", partyLean: "Split" },
      { name: "Computer & Communications Industry Assn PAC", amount: "$2.2M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Maria Cantwell", party: "D", office: "U.S. Senate", totalReceived: "$880K" },
      { name: "Roger Wicker", party: "R", office: "U.S. Senate", totalReceived: "$820K" },
      { name: "Amy Klobuchar", party: "D", office: "U.S. Senate", totalReceived: "$760K" },
      { name: "Brian Schatz", party: "D", office: "U.S. Senate", totalReceived: "$680K" },
      { name: "Marsha Blackburn", party: "R", office: "U.S. Senate", totalReceived: "$580K" },
    ],
    interestBreakdown: [
      { label: "Antitrust Opposition (Big Tech)", pct: 30 },
      { label: "State Social Media Law Challenges", pct: 26 },
      { label: "First Amendment / Content Moderation", pct: 22 },
      { label: "Data Privacy & AI Regulation", pct: 14 },
      { label: "Section 230 Liability Shield", pct: 8 },
    ],
  },
  {
    name: "American Hospital Association",
    tag: "AHA",
    acronym: "AHA",
    description: "The American Hospital Association represents nearly 5,000 hospitals and health systems and spends $20–$40M annually lobbying on Medicare and Medicaid reimbursement rates, surprise billing legislation, hospital merger oversight, and workforce staffing rules. While AHA publicly supports expanded healthcare coverage, it consistently opposes cost-containment measures that would reduce hospital revenue, including site-neutral payment reforms and price transparency mandates.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$20M–$40M",
    partySplitDem: 58,
    partySplitRep: 42,
    website: "https://www.aha.org",
    headquarters: "Chicago, IL",
    industry: "hospitals",
    influenceScore: -10,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-hospital-assn/summary?id=d000000103",
    topPacs: [
      { name: "American Hospital Assn PAC", amount: "$4.9M", partyLean: "D" },
      { name: "HCA Healthcare PAC", amount: "$4.0M", partyLean: "R" },
      { name: "CommonSpirit Health PAC", amount: "$2.8M", partyLean: "D" },
      { name: "Ascension Health PAC", amount: "$2.5M", partyLean: "Split" },
      { name: "Tenet Healthcare PAC", amount: "$2.2M", partyLean: "Split" },
    ],
    topCandidates: [
      { name: "Richard Neal", party: "D", office: "U.S. House", totalReceived: "$760K" },
      { name: "Greg Walden", party: "R", office: "U.S. House", totalReceived: "$700K" },
      { name: "Frank Pallone", party: "D", office: "U.S. House", totalReceived: "$640K" },
      { name: "Chuck Grassley", party: "R", office: "U.S. Senate", totalReceived: "$590K" },
      { name: "Michael Burgess", party: "R", office: "U.S. House", totalReceived: "$520K" },
    ],
    interestBreakdown: [
      { label: "Medicare Reimbursement Rates", pct: 34 },
      { label: "Surprise Billing & Price Transparency", pct: 22 },
      { label: "Hospital Merger Antitrust", pct: 18 },
      { label: "Medicaid Funding", pct: 16 },
      { label: "Workforce & Nurse Staffing Rules", pct: 10 },
    ],
  },
  {
    name: "National Federation of Independent Business",
    tag: "NFIB",
    acronym: "NFIB",
    description: "The National Federation of Independent Business represents 300,000 small business owners and is one of Washington's most effective conservative lobbying forces. It spends $5–$15M annually opposing minimum wage increases, mandated paid leave, employer health insurance requirements, and business regulations. The NFIB was a key plaintiff in NFIB v. Sebelius (2012), successfully striking down the ACA's Medicaid expansion mandate, and later in NFIB v. OSHA blocking the federal vaccine mandate.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$5M–$15M",
    partySplitDem: 8,
    partySplitRep: 92,
    website: "https://www.nfib.com",
    headquarters: "Nashville, TN",
    industry: "small_business",
    influenceScore: -20,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/nfib/summary?id=d000000114",
    topPacs: [
      { name: "NFIB Political Action Committee", amount: "$6.4M", partyLean: "R" },
      { name: "National Small Business Association PAC", amount: "$2.4M", partyLean: "R" },
      { name: "Main Street Alliance PAC", amount: "$1.6M", partyLean: "D" },
      { name: "Job Creators Network PAC", amount: "$1.2M", partyLean: "R" },
      { name: "Small Business Majority Action PAC", amount: "$0.8M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", office: "U.S. Senate", totalReceived: "$840K" },
      { name: "Rob Portman", party: "R", office: "U.S. Senate", totalReceived: "$720K" },
      { name: "John Cornyn", party: "R", office: "U.S. Senate", totalReceived: "$660K" },
      { name: "Steve Scalise", party: "R", office: "U.S. House", totalReceived: "$580K" },
      { name: "Thom Tillis", party: "R", office: "U.S. Senate", totalReceived: "$520K" },
    ],
    interestBreakdown: [
      { label: "Minimum Wage Opposition", pct: 28 },
      { label: "Employer Mandate & ACA Rules", pct: 24 },
      { label: "Regulation & Paperwork Burden", pct: 22 },
      { label: "Tax Cuts (pass-through deductions)", pct: 16 },
      { label: "Paid Leave & Benefits Mandates", pct: 10 },
    ],
  },
  {
    name: "American Federation of Teachers",
    tag: "AFT",
    acronym: "AFT",
    description: "The American Federation of Teachers represents 1.7 million members concentrated in urban school districts and higher education, spending $20–$40M per cycle on Democratic campaigns. Unlike the NEA, AFT has been more open to some school reform discussions but remains a fierce opponent of school vouchers, privatization, and standardized testing regimes. Led by Randi Weingarten, AFT was a central voice during the Covid-19 school reopening controversy.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$40M",
    partySplitDem: 97,
    partySplitRep: 3,
    website: "https://www.aft.org",
    headquarters: "Washington, DC",
    industry: "education",
    influenceScore: 26,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/american-federation-of-teachers/summary?id=d000000083",
    topPacs: [
      { name: "AFT Political Fund", amount: "$22.4M", partyLean: "D" },
      { name: "AFT Solidarity PAC", amount: "$8.8M", partyLean: "D" },
      { name: "AFT Higher Education PAC", amount: "$3.4M", partyLean: "D" },
      { name: "AFT Healthcare PAC", amount: "$2.6M", partyLean: "D" },
      { name: "AFT COPE (state political fund)", amount: "$4.2M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.1M" },
      { name: "Patty Murray", party: "D", office: "U.S. Senate", totalReceived: "$1.1M" },
      { name: "Raphael Warnock", party: "D", office: "U.S. Senate", totalReceived: "$920K" },
      { name: "John Fetterman", party: "D", office: "U.S. Senate", totalReceived: "$840K" },
      { name: "Bernie Sanders", party: "D", office: "U.S. Senate", totalReceived: "$780K" },
    ],
    interestBreakdown: [
      { label: "School Voucher & Privatization Opposition", pct: 30 },
      { label: "Teacher Pay & Pension Protection", pct: 26 },
      { label: "Higher Education Funding", pct: 20 },
      { label: "Student Loan Debt Relief", pct: 14 },
      { label: "Standardized Testing Opposition", pct: 10 },
    ],
  },
  {
    name: "National Farmers Union",
    tag: "NFU",
    acronym: "NFU",
    description: "The National Farmers Union represents 200,000 family farmers and ranchers and is the progressive counterpart to the American Farm Bureau, prioritizing fair prices, antitrust enforcement against agribusiness consolidation, and rural community development over subsidies for industrial operations. It spends $3–$8M annually supporting candidates who back price-parity programs, combat corporate agriculture monopolies, and invest in rural infrastructure. NFU has long championed the interests of smaller independent farmers over large agribusiness.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$3M–$8M",
    partySplitDem: 65,
    partySplitRep: 35,
    website: "https://nfu.org",
    headquarters: "Washington, DC",
    industry: "agriculture",
    influenceScore: 18,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/national-farmers-union/summary?id=d000000491",
    topPacs: [
      { name: "National Farmers Union PAC", amount: "$2.8M", partyLean: "D" },
      { name: "Farm Aid Advocacy Fund", amount: "$1.2M", partyLean: "D" },
      { name: "Rural Advancement Foundation Int'l PAC", amount: "$0.8M", partyLean: "D" },
      { name: "National Sustainable Agriculture Coalition PAC", amount: "$0.6M", partyLean: "D" },
      { name: "American Farmers & Ranchers PAC", amount: "$0.5M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Debbie Stabenow", party: "D", office: "U.S. Senate", totalReceived: "$680K" },
      { name: "Amy Klobuchar", party: "D", office: "U.S. Senate", totalReceived: "$600K" },
      { name: "Sherrod Brown", party: "D", office: "U.S. Senate", totalReceived: "$540K" },
      { name: "Jon Tester", party: "D", office: "U.S. Senate", totalReceived: "$480K" },
      { name: "Dick Durbin", party: "D", office: "U.S. Senate", totalReceived: "$420K" },
    ],
    interestBreakdown: [
      { label: "Antitrust Against Agribusiness Consolidation", pct: 30 },
      { label: "Fair Farm Prices & Parity Programs", pct: 26 },
      { label: "Rural Infrastructure & Broadband", pct: 20 },
      { label: "Organic & Sustainable Farming Support", pct: 14 },
      { label: "Country-of-Origin Labeling", pct: 10 },
    ],
  },
  {
    name: "United Auto Workers",
    tag: "UAW",
    acronym: "UAW",
    description: "The United Auto Workers represents 400,000 active workers and nearly 600,000 retired workers in auto manufacturing, aerospace, and higher education. After a transformative 2023 contract campaign against GM, Ford, and Stellantis — securing 25% wage increases — the UAW re-emerged as one of America's most aggressive unions. It spends $20–$40M per cycle on Democratic campaigns and has begun organizing non-union plants including Tesla, Volkswagen, and Mercedes facilities.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$40M",
    partySplitDem: 95,
    partySplitRep: 5,
    website: "https://uaw.org",
    headquarters: "Detroit, MI",
    industry: "manufacturing",
    influenceScore: 32,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/united-auto-workers/summary?id=d000000090",
    topPacs: [
      { name: "UAW V-CAP (Voluntary Community Action Program)", amount: "$18.4M", partyLean: "D" },
      { name: "UAW Political Action PAC", amount: "$8.6M", partyLean: "D" },
      { name: "UAW Region 1 PAC (Michigan)", amount: "$3.2M", partyLean: "D" },
      { name: "Autoworkers Community Action Network", amount: "$2.4M", partyLean: "D" },
      { name: "International Union PAC (combined)", amount: "$1.8M", partyLean: "D" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", office: "President", totalReceived: "$2.4M" },
      { name: "Debbie Stabenow", party: "D", office: "U.S. Senate", totalReceived: "$1.4M" },
      { name: "Gary Peters", party: "D", office: "U.S. Senate", totalReceived: "$1.2M" },
      { name: "Sherrod Brown", party: "D", office: "U.S. Senate", totalReceived: "$1.0M" },
      { name: "Haley Stevens", party: "D", office: "U.S. House", totalReceived: "$780K" },
    ],
    interestBreakdown: [
      { label: "Auto Worker Wages & Benefits", pct: 32 },
      { label: "EV Transition Worker Protections", pct: 24 },
      { label: "Manufacturing Trade Policy (anti-offshoring)", pct: 22 },
      { label: "Organizing Rights & PRO Act", pct: 14 },
      { label: "Pension & Retiree Benefits", pct: 8 },
    ],
  },
];

export async function seedLobbies(): Promise<void> {
  log(`Deleting existing lobby records to replace with 35-org diverse list...`);
  await db.execute(sql`DELETE FROM special_interest_groups WHERE category = 'lobby'`);

  log(`Seeding ${SECTORS.length} lobby organizations...`);

  for (const sector of SECTORS) {
    await db.execute(sql`
      INSERT INTO special_interest_groups (
        id, name, acronym, tag, description, category, sentiment,
        website, headquarters, industry,
        data_source_name, data_source_url,
        influence_score,
        spend_range, party_split_dem, party_split_rep,
        top_pacs, top_candidates, interest_breakdown,
        is_active, created_at, updated_at
      )
      VALUES (
        gen_random_uuid(),
        ${sector.name}, ${sector.acronym ?? null}, ${sector.tag},
        ${sector.description}, ${sector.category}, ${sector.sentiment},
        ${sector.website}, ${sector.headquarters}, ${sector.industry},
        ${sector.dataSourceName}, ${sector.dataSourceUrl},
        ${sector.influenceScore},
        ${sector.spendRange},
        ${sector.partySplitDem},
        ${sector.partySplitRep},
        ${JSON.stringify(sector.topPacs)}::jsonb,
        ${JSON.stringify(sector.topCandidates)}::jsonb,
        ${JSON.stringify(sector.interestBreakdown)}::jsonb,
        true, NOW(), NOW()
      )
      ON CONFLICT (tag) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        sentiment = EXCLUDED.sentiment,
        spend_range = EXCLUDED.spend_range,
        party_split_dem = EXCLUDED.party_split_dem,
        party_split_rep = EXCLUDED.party_split_rep,
        top_pacs = EXCLUDED.top_pacs,
        top_candidates = EXCLUDED.top_candidates,
        interest_breakdown = EXCLUDED.interest_breakdown,
        influence_score = EXCLUDED.influence_score,
        updated_at = NOW()
    `);
  }

  log(`Lobby seed complete — ${SECTORS.length} organizations upserted`);
}
