import { db } from "./db";
import { sql } from "drizzle-orm";

function log(msg: string) {
  const time = new Date().toLocaleTimeString("en-US", { hour12: false });
  console.log(`${time} [lobby-seed] ${msg}`);
}

type SectorEntry = {
  name: string;
  tag: string;
  acronym?: string;
  description: string;
  category: string;
  sentiment: string;
  spendRange: string;
  partySplitDem: number;
  partySplitRep: number;
  website: string;
  headquarters: string;
  industry: string;
  influenceScore: number;
  dataSourceName: string;
  dataSourceUrl: string;
  topPacs: Array<{ name: string; amount: string }>;
  topCandidates: Array<{ name: string; party: string; state: string; amount: string }>;
  interestBreakdown: Array<{ label: string; pct: number }>;
};

const SECTORS: SectorEntry[] = [
  {
    name: "Pharmaceuticals & Health Products",
    tag: "PHARMA",
    acronym: "PhRMA",
    description: "The pharmaceutical and health products industry is the single largest lobbying sector, spending $350–$450M annually. It aggressively fights drug price negotiation, Medicare bargaining power, patent reforms, and importation from Canada. PhRMA and individual drug companies together wield enormous influence to protect billion-dollar profit margins.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$350M–$450M",
    partySplitDem: 54,
    partySplitRep: 46,
    website: "https://www.phrma.org",
    headquarters: "Washington, DC",
    industry: "pharma",
    influenceScore: -30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=H04",
    topPacs: [
      { name: "PhRMA PAC", amount: "$8.2M" },
      { name: "Pfizer Inc PAC", amount: "$6.1M" },
      { name: "Eli Lilly & Co PAC", amount: "$5.4M" },
      { name: "Abbott Laboratories PAC", amount: "$4.8M" },
      { name: "Johnson & Johnson PAC", amount: "$4.2M" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$1.2M" },
      { name: "Pat Toomey", party: "R", state: "PA", amount: "$980K" },
      { name: "Kyrsten Sinema", party: "D", state: "AZ", amount: "$860K" },
      { name: "Joe Manchin", party: "D", state: "WV", amount: "$740K" },
      { name: "Chuck Grassley", party: "R", state: "IA", amount: "$680K" },
    ],
    interestBreakdown: [
      { label: "Drug Pricing Policy", pct: 32 },
      { label: "FDA Regulation", pct: 24 },
      { label: "Patent & IP Reform", pct: 20 },
      { label: "Medicare/Medicaid", pct: 14 },
      { label: "Other Health Policy", pct: 10 },
    ],
  },
  {
    name: "Insurance",
    tag: "INSURANCE",
    acronym: "AHIP",
    description: "The insurance industry spends $250–$350M annually to protect its dominant position in health, life, auto, and property markets. It opposes a public health insurance option, reinsurance requirements, and rate transparency mandates. Major insurers like UnitedHealth and Aetna lobby both parties extensively.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$250M–$350M",
    partySplitDem: 48,
    partySplitRep: 52,
    website: "https://www.ahip.org",
    headquarters: "Washington, DC",
    industry: "insurance",
    influenceScore: -25,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=F09",
    topPacs: [
      { name: "UnitedHealth Group PAC", amount: "$5.8M" },
      { name: "Blue Cross/Blue Shield PAC", amount: "$5.2M" },
      { name: "Cigna Corp PAC", amount: "$4.1M" },
      { name: "Aetna Inc PAC", amount: "$3.9M" },
      { name: "Allstate Insurance PAC", amount: "$3.2M" },
    ],
    topCandidates: [
      { name: "Kevin McCarthy", party: "R", state: "CA", amount: "$920K" },
      { name: "Steny Hoyer", party: "D", state: "MD", amount: "$780K" },
      { name: "Cathy McMorris Rodgers", party: "R", state: "WA", amount: "$650K" },
      { name: "Richard Neal", party: "D", state: "MA", amount: "$610K" },
      { name: "Mike Crapo", party: "R", state: "ID", amount: "$570K" },
    ],
    interestBreakdown: [
      { label: "Health Insurance Markets", pct: 38 },
      { label: "ACA & Public Option", pct: 22 },
      { label: "Property & Casualty", pct: 18 },
      { label: "Financial Regulation", pct: 12 },
      { label: "Medicaid Managed Care", pct: 10 },
    ],
  },
  {
    name: "Hospitals & Health Systems",
    tag: "HOSPITALS",
    acronym: "AHA",
    description: "Hospitals and health systems form one of the most powerful and bipartisan lobbying blocs, spending $200–$300M annually. The American Hospital Association and individual health systems lobby on Medicare reimbursement rates, surprise billing, hospital merger oversight, and workforce regulations. Their local economic footprint gives them leverage with members of both parties.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$200M–$300M",
    partySplitDem: 58,
    partySplitRep: 42,
    website: "https://www.aha.org",
    headquarters: "Chicago, IL",
    industry: "healthcare",
    influenceScore: -10,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=H02",
    topPacs: [
      { name: "American Hospital Assn PAC", amount: "$4.8M" },
      { name: "HCA Inc PAC", amount: "$3.9M" },
      { name: "CommonSpirit Health PAC", amount: "$2.7M" },
      { name: "Ascension Health PAC", amount: "$2.4M" },
      { name: "Tenet Healthcare PAC", amount: "$2.1M" },
    ],
    topCandidates: [
      { name: "Richard Neal", party: "D", state: "MA", amount: "$740K" },
      { name: "Greg Walden", party: "R", state: "OR", amount: "$680K" },
      { name: "Frank Pallone", party: "D", state: "NJ", amount: "$620K" },
      { name: "Chuck Grassley", party: "R", state: "IA", amount: "$580K" },
      { name: "Michael Burgess", party: "R", state: "TX", amount: "$510K" },
    ],
    interestBreakdown: [
      { label: "Medicare Reimbursement", pct: 35 },
      { label: "Hospital Mergers & Oversight", pct: 20 },
      { label: "Medicaid Funding", pct: 18 },
      { label: "Workforce & Staffing", pct: 15 },
      { label: "Surprise Billing", pct: 12 },
    ],
  },
  {
    name: "Tech / Electronics / Software",
    tag: "TECH",
    acronym: "CCIA",
    description: "The technology sector spends $200–$300M annually and has become one of the dominant lobbying forces in Washington. Big Tech companies — Meta, Google, Amazon, Apple, Microsoft — lobby on antitrust, data privacy, AI regulation, immigration (H-1B visas), and content moderation. Tech spending has grown dramatically since 2016 as regulatory scrutiny has intensified.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$200M–$300M",
    partySplitDem: 63,
    partySplitRep: 37,
    website: "https://www.ccia.org",
    headquarters: "Washington, DC",
    industry: "technology",
    influenceScore: -5,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=B12",
    topPacs: [
      { name: "Amazon.com Inc PAC", amount: "$6.4M" },
      { name: "Google / Alphabet PAC", amount: "$5.8M" },
      { name: "Meta Platforms PAC", amount: "$5.2M" },
      { name: "Microsoft Corp PAC", amount: "$4.9M" },
      { name: "Apple Inc PAC", amount: "$3.7M" },
    ],
    topCandidates: [
      { name: "Maria Cantwell", party: "D", state: "WA", amount: "$820K" },
      { name: "Ro Khanna", party: "D", state: "CA", amount: "$740K" },
      { name: "Roger Wicker", party: "R", state: "MS", amount: "$680K" },
      { name: "Amy Klobuchar", party: "D", state: "MN", amount: "$610K" },
      { name: "Brian Schatz", party: "D", state: "HI", amount: "$560K" },
    ],
    interestBreakdown: [
      { label: "Antitrust & Competition", pct: 28 },
      { label: "Data Privacy & AI", pct: 25 },
      { label: "Copyright & IP", pct: 18 },
      { label: "Immigration (H-1B)", pct: 16 },
      { label: "Content Moderation", pct: 13 },
    ],
  },
  {
    name: "Business Associations / Chamber Groups",
    tag: "BIZ_ASSOC",
    acronym: "USCC",
    description: "Business associations and chamber groups spend $180–$280M annually, led by the U.S. Chamber of Commerce — the largest single lobbying entity in the country. These groups oppose regulations across virtually every sector, fight minimum wage increases, block climate legislation, and push for corporate tax cuts. Their broad membership gives them an outsized voice in Republican and moderate Democratic circles.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$180M–$280M",
    partySplitDem: 22,
    partySplitRep: 78,
    website: "https://www.uschamber.com",
    headquarters: "Washington, DC",
    industry: "business",
    influenceScore: -35,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=A00",
    topPacs: [
      { name: "US Chamber of Commerce", amount: "$82M" },
      { name: "Business Roundtable", amount: "$28M" },
      { name: "National Assn of Manufacturers", amount: "$14M" },
      { name: "NFIB PAC", amount: "$8.2M" },
      { name: "Business-Industry PAC", amount: "$4.1M" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$1.4M" },
      { name: "Rob Portman", party: "R", state: "OH", amount: "$1.1M" },
      { name: "John Cornyn", party: "R", state: "TX", amount: "$980K" },
      { name: "Thom Tillis", party: "R", state: "NC", amount: "$840K" },
      { name: "Steve Scalise", party: "R", state: "LA", amount: "$720K" },
    ],
    interestBreakdown: [
      { label: "Deregulation", pct: 30 },
      { label: "Tax Policy", pct: 25 },
      { label: "Labor & Workforce", pct: 20 },
      { label: "Trade & Tariffs", pct: 15 },
      { label: "Environmental Rules", pct: 10 },
    ],
  },
  {
    name: "Finance / Securities / Investment",
    tag: "FINANCE",
    acronym: "SIFMA",
    description: "Wall Street and the broader financial sector spend $175–$275M annually lobbying against financial regulation, consumer protections, and oversight reforms. Following the 2008 crash, the industry fought Dodd-Frank implementation for years. Today it opposes CFPB enforcement, fiduciary rules, and short-seller regulations. Investment banks, hedge funds, and private equity firms all contribute heavily.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$175M–$275M",
    partySplitDem: 43,
    partySplitRep: 57,
    website: "https://www.sifma.org",
    headquarters: "New York, NY",
    industry: "finance",
    influenceScore: -30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=F07",
    topPacs: [
      { name: "Goldman Sachs PAC", amount: "$5.4M" },
      { name: "JPMorgan Chase PAC", amount: "$5.1M" },
      { name: "Blackstone Group PAC", amount: "$4.8M" },
      { name: "Bank of America PAC", amount: "$4.2M" },
      { name: "Citadel LLC PAC", amount: "$3.9M" },
    ],
    topCandidates: [
      { name: "Chuck Schumer", party: "D", state: "NY", amount: "$1.1M" },
      { name: "Sherrod Brown", party: "D", state: "OH", amount: "$890K" },
      { name: "Pat Toomey", party: "R", state: "PA", amount: "$840K" },
      { name: "Tim Scott", party: "R", state: "SC", amount: "$780K" },
      { name: "Mike Crapo", party: "R", state: "ID", amount: "$720K" },
    ],
    interestBreakdown: [
      { label: "Financial Regulation", pct: 30 },
      { label: "Tax Policy", pct: 22 },
      { label: "Consumer Protection Rules", pct: 18 },
      { label: "Crypto & Fintech", pct: 16 },
      { label: "Retirement & Pension Rules", pct: 14 },
    ],
  },
  {
    name: "Real Estate / Realtors / Developers",
    tag: "REAL_ESTATE",
    acronym: "NAR",
    description: "The real estate sector, led by the National Association of Realtors — the largest PAC donor in the U.S. — spends $150–$250M annually. It lobbies to protect the mortgage interest deduction, oppose affordable housing mandates, weaken rent control measures, and influence zoning laws. NAR has the largest PAC in the country and donates to both parties heavily.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$150M–$250M",
    partySplitDem: 44,
    partySplitRep: 56,
    website: "https://www.nar.realtor",
    headquarters: "Chicago, IL",
    industry: "real_estate",
    influenceScore: -15,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=F10",
    topPacs: [
      { name: "National Assn of Realtors PAC", amount: "$18.4M" },
      { name: "National Assn of Home Builders PAC", amount: "$6.2M" },
      { name: "Blackstone Real Estate PAC", amount: "$3.8M" },
      { name: "CBRE Group PAC", amount: "$2.4M" },
      { name: "Apartment Investment PAC", amount: "$1.9M" },
    ],
    topCandidates: [
      { name: "Kevin McCarthy", party: "R", state: "CA", amount: "$960K" },
      { name: "Steny Hoyer", party: "D", state: "MD", amount: "$820K" },
      { name: "Bob Menendez", party: "D", state: "NJ", amount: "$740K" },
      { name: "Roger Williams", party: "R", state: "TX", amount: "$680K" },
      { name: "David Scott", party: "D", state: "GA", amount: "$610K" },
    ],
    interestBreakdown: [
      { label: "Mortgage Interest Deduction", pct: 28 },
      { label: "Zoning & Land Use", pct: 22 },
      { label: "Housing Finance (GSEs)", pct: 20 },
      { label: "Affordable Housing Policy", pct: 18 },
      { label: "Commercial Real Estate Tax", pct: 12 },
    ],
  },
  {
    name: "Electric Utilities",
    tag: "ELECTRIC_UTIL",
    acronym: "EEI",
    description: "Electric utilities spend $140–$220M annually, primarily to protect rate structures, resist distributed energy competition, and shape clean energy transition policy. Investor-owned utilities use lobbying to delay renewable mandates and protect guaranteed profit margins. Edison Electric Institute coordinates industry-wide strategy on grid regulation and coal/natural gas plant retirements.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$140M–$220M",
    partySplitDem: 40,
    partySplitRep: 60,
    website: "https://www.eei.org",
    headquarters: "Washington, DC",
    industry: "utilities",
    influenceScore: -20,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=E08",
    topPacs: [
      { name: "NextEra Energy PAC", amount: "$4.6M" },
      { name: "Southern Co PAC", amount: "$4.1M" },
      { name: "Duke Energy PAC", amount: "$3.8M" },
      { name: "Dominion Energy PAC", amount: "$3.4M" },
      { name: "Exelon Corp PAC", amount: "$2.9M" },
    ],
    topCandidates: [
      { name: "Shelley Moore Capito", party: "R", state: "WV", amount: "$820K" },
      { name: "Joe Manchin", party: "D", state: "WV", amount: "$760K" },
      { name: "Bill Cassidy", party: "R", state: "LA", amount: "$680K" },
      { name: "John Barrasso", party: "R", state: "WY", amount: "$620K" },
      { name: "Lisa Murkowski", party: "R", state: "AK", amount: "$570K" },
    ],
    interestBreakdown: [
      { label: "Rate Regulation", pct: 30 },
      { label: "Grid Modernization", pct: 24 },
      { label: "Renewable Standards", pct: 22 },
      { label: "Nuclear Policy", pct: 14 },
      { label: "Environmental Compliance", pct: 10 },
    ],
  },
  {
    name: "Oil & Gas",
    tag: "OIL_GAS",
    acronym: "API",
    description: "The oil and gas industry spends $125–$200M annually on lobbying to protect fossil fuel subsidies, oppose carbon taxes and emissions standards, block clean energy mandates, and fight environmental regulation. The American Petroleum Institute leads the sector's Washington presence. Companies like ExxonMobil, Chevron, and Koch Industries have spent decades funding climate denial and anti-regulation campaigns.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$125M–$200M",
    partySplitDem: 15,
    partySplitRep: 85,
    website: "https://www.api.org",
    headquarters: "Washington, DC",
    industry: "oil_gas",
    influenceScore: -45,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=E01",
    topPacs: [
      { name: "Koch Industries PAC", amount: "$9.2M" },
      { name: "ExxonMobil Corp PAC", amount: "$5.8M" },
      { name: "Chevron Corp PAC", amount: "$4.9M" },
      { name: "American Petroleum Inst PAC", amount: "$4.2M" },
      { name: "ConocoPhillips PAC", amount: "$3.6M" },
    ],
    topCandidates: [
      { name: "John Cornyn", party: "R", state: "TX", amount: "$1.3M" },
      { name: "Ted Cruz", party: "R", state: "TX", amount: "$1.1M" },
      { name: "Kevin Cramer", party: "R", state: "ND", amount: "$980K" },
      { name: "John Barrasso", party: "R", state: "WY", amount: "$890K" },
      { name: "Steve Scalise", party: "R", state: "LA", amount: "$820K" },
    ],
    interestBreakdown: [
      { label: "Fossil Fuel Subsidies", pct: 28 },
      { label: "Emissions & EPA Rules", pct: 26 },
      { label: "Offshore Drilling Rights", pct: 18 },
      { label: "Pipeline Permitting", pct: 16 },
      { label: "LNG Export Policy", pct: 12 },
    ],
  },
  {
    name: "Defense Contractors / Aerospace",
    tag: "DEFENSE",
    acronym: "AIA",
    description: "Defense contractors and aerospace companies spend $120–$200M annually to secure Pentagon contracts, oppose defense budget cuts, and shape weapons procurement policy. The sector enjoys bipartisan support as major contractors operate in nearly every congressional district. Lockheed Martin, Raytheon, Boeing, and Northrop Grumman are the top spenders, and the revolving door between the Pentagon and industry is well-documented.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$120M–$200M",
    partySplitDem: 48,
    partySplitRep: 52,
    website: "https://www.aia-aerospace.org",
    headquarters: "Arlington, VA",
    industry: "defense",
    influenceScore: -28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=D",
    topPacs: [
      { name: "Lockheed Martin PAC", amount: "$5.6M" },
      { name: "Raytheon Technologies PAC", amount: "$5.1M" },
      { name: "Boeing Co PAC", amount: "$4.8M" },
      { name: "Northrop Grumman PAC", amount: "$4.4M" },
      { name: "General Dynamics PAC", amount: "$3.9M" },
    ],
    topCandidates: [
      { name: "Jack Reed", party: "D", state: "RI", amount: "$940K" },
      { name: "James Inhofe", party: "R", state: "OK", amount: "$880K" },
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$820K" },
      { name: "Adam Smith", party: "D", state: "WA", amount: "$760K" },
      { name: "Mike Turner", party: "R", state: "OH", amount: "$690K" },
    ],
    interestBreakdown: [
      { label: "Weapons Procurement", pct: 35 },
      { label: "Pentagon Budget", pct: 25 },
      { label: "Export Controls", pct: 18 },
      { label: "Space & Satellite", pct: 12 },
      { label: "Cybersecurity Contracts", pct: 10 },
    ],
  },
  {
    name: "Telecom / Broadband / Cable",
    tag: "TELECOM",
    acronym: "NCTA",
    description: "Telecom, broadband, and cable companies spend $100–$175M annually, primarily opposing net neutrality, strong broadband regulation, and municipal broadband competition. AT&T, Comcast, Verizon, and Charter collectively represent one of the most consistently powerful lobbying blocs. The industry successfully blocked FCC reclassification of broadband under Title II for years.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$100M–$175M",
    partySplitDem: 38,
    partySplitRep: 62,
    website: "https://www.ncta.com",
    headquarters: "Washington, DC",
    industry: "telecom",
    influenceScore: -25,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=B09",
    topPacs: [
      { name: "AT&T Inc PAC", amount: "$6.4M" },
      { name: "Comcast Corp PAC", amount: "$5.8M" },
      { name: "Verizon Communications PAC", amount: "$5.2M" },
      { name: "Charter Communications PAC", amount: "$3.6M" },
      { name: "T-Mobile USA PAC", amount: "$2.9M" },
    ],
    topCandidates: [
      { name: "Greg Walden", party: "R", state: "OR", amount: "$880K" },
      { name: "Frank Pallone", party: "D", state: "NJ", amount: "$820K" },
      { name: "Roger Wicker", party: "R", state: "MS", amount: "$760K" },
      { name: "Jacky Rosen", party: "D", state: "NV", amount: "$640K" },
      { name: "Cathy McMorris Rodgers", party: "R", state: "WA", amount: "$610K" },
    ],
    interestBreakdown: [
      { label: "Net Neutrality", pct: 30 },
      { label: "Spectrum & Wireless Policy", pct: 26 },
      { label: "Broadband Subsidies", pct: 20 },
      { label: "Cable Regulation", pct: 14 },
      { label: "Privacy Rules", pct: 10 },
    ],
  },
  {
    name: "Misc. Manufacturing",
    tag: "MANUFACTURING",
    acronym: "NAM",
    description: "The broader manufacturing sector spends $100–$175M annually, coordinated largely by the National Association of Manufacturers. It lobbies against environmental regulations, occupational safety rules, trade tariffs that raise input costs, and labor protections. Manufacturing is a bipartisan constituency that both parties court but whose executives frequently align with deregulatory Republican priorities.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$100M–$175M",
    partySplitDem: 36,
    partySplitRep: 64,
    website: "https://www.nam.org",
    headquarters: "Washington, DC",
    industry: "manufacturing",
    influenceScore: -18,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=N",
    topPacs: [
      { name: "National Assn of Manufacturers PAC", amount: "$4.8M" },
      { name: "Honeywell International PAC", amount: "$4.2M" },
      { name: "3M Co PAC", amount: "$3.6M" },
      { name: "Caterpillar Inc PAC", amount: "$3.2M" },
      { name: "Emerson Electric PAC", amount: "$2.8M" },
    ],
    topCandidates: [
      { name: "Rob Portman", party: "R", state: "OH", amount: "$820K" },
      { name: "Debbie Stabenow", party: "D", state: "MI", amount: "$740K" },
      { name: "Patrick Toomey", party: "R", state: "PA", amount: "$680K" },
      { name: "Tim Walberg", party: "R", state: "MI", amount: "$620K" },
      { name: "Sherrod Brown", party: "D", state: "OH", amount: "$580K" },
    ],
    interestBreakdown: [
      { label: "Environmental & EPA Rules", pct: 28 },
      { label: "Trade & Tariff Policy", pct: 24 },
      { label: "Labor & OSHA Standards", pct: 22 },
      { label: "Tax & Depreciation", pct: 16 },
      { label: "Energy Costs", pct: 10 },
    ],
  },
  {
    name: "Transportation / Airlines / Rail / Shipping",
    tag: "TRANSPORT",
    acronym: "ATA",
    description: "The transportation sector — airlines, railroads, shipping companies, and trucking — spends $90–$160M annually. Airlines lobby on slot rules and mergers; railroads oppose safety mandates; shipping companies resist cabotage reform. The sector benefits from enormous public infrastructure subsidies while lobbying against worker protections and liability for accidents.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$90M–$160M",
    partySplitDem: 42,
    partySplitRep: 58,
    website: "https://www.trucking.org",
    headquarters: "Arlington, VA",
    industry: "transportation",
    influenceScore: -15,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=M",
    topPacs: [
      { name: "United Parcel Service PAC", amount: "$4.4M" },
      { name: "American Airlines Group PAC", amount: "$3.8M" },
      { name: "FedEx Corp PAC", amount: "$3.4M" },
      { name: "Delta Air Lines PAC", amount: "$3.1M" },
      { name: "Norfolk Southern PAC", amount: "$2.6M" },
    ],
    topCandidates: [
      { name: "Sam Graves", party: "R", state: "MO", amount: "$780K" },
      { name: "Peter DeFazio", party: "D", state: "OR", amount: "$720K" },
      { name: "John Thune", party: "R", state: "SD", amount: "$660K" },
      { name: "Maria Cantwell", party: "D", state: "WA", amount: "$610K" },
      { name: "Roger Wicker", party: "R", state: "MS", amount: "$580K" },
    ],
    interestBreakdown: [
      { label: "Safety & Hours-of-Service", pct: 25 },
      { label: "Infrastructure Funding", pct: 22 },
      { label: "Fuel Taxes & Fees", pct: 20 },
      { label: "Labor & Crew Rules", pct: 18 },
      { label: "Emissions Standards", pct: 15 },
    ],
  },
  {
    name: "Automotive / Dealers / EV Policy",
    tag: "AUTO",
    acronym: "NADA",
    description: "The automotive industry — manufacturers, dealers, and suppliers — spends $80–$150M annually. Automakers lobby on fuel economy standards, EV mandates, tariffs on steel and auto parts, and dealer franchise laws. The sector is split between traditional manufacturers resisting rapid EV transition timelines and newer EV-focused companies pushing for supportive infrastructure funding.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$80M–$150M",
    partySplitDem: 40,
    partySplitRep: 60,
    website: "https://www.nada.org",
    headquarters: "Tysons, VA",
    industry: "automotive",
    influenceScore: -12,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=T01",
    topPacs: [
      { name: "General Motors PAC", amount: "$4.2M" },
      { name: "Ford Motor Co PAC", amount: "$3.9M" },
      { name: "National Auto Dealers Assn PAC", amount: "$3.6M" },
      { name: "Toyota Motor North America PAC", amount: "$2.8M" },
      { name: "AutoNation Inc PAC", amount: "$1.9M" },
    ],
    topCandidates: [
      { name: "Debbie Stabenow", party: "D", state: "MI", amount: "$780K" },
      { name: "Gary Peters", party: "D", state: "MI", amount: "$720K" },
      { name: "John Dingell Jr", party: "D", state: "MI", amount: "$680K" },
      { name: "Mike Gallagher", party: "R", state: "WI", amount: "$580K" },
      { name: "Fred Upton", party: "R", state: "MI", amount: "$540K" },
    ],
    interestBreakdown: [
      { label: "Fuel Economy (CAFE) Standards", pct: 30 },
      { label: "EV Mandates & Incentives", pct: 26 },
      { label: "Tariffs & Trade", pct: 20 },
      { label: "Dealer Franchise Laws", pct: 14 },
      { label: "Safety Regulations", pct: 10 },
    ],
  },
  {
    name: "Agriculture / Farm Bureau / Commodities",
    tag: "AGRICULTURE",
    acronym: "AFBF",
    description: "Agriculture lobbying — dominated by the American Farm Bureau, commodity groups, and agribusiness giants — spends $80–$150M annually. The sector secures enormous farm subsidies, crop insurance programs, and trade protections through the Farm Bill. Agribusiness opposes GMO labeling, stricter pesticide rules, antitrust action on consolidation, and immigration enforcement that threatens farm labor.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$80M–$150M",
    partySplitDem: 35,
    partySplitRep: 65,
    website: "https://www.fb.org",
    headquarters: "Washington, DC",
    industry: "agriculture",
    influenceScore: -12,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=A",
    topPacs: [
      { name: "American Farm Bureau PAC", amount: "$5.2M" },
      { name: "Archer-Daniels-Midland PAC", amount: "$3.8M" },
      { name: "National Corn Growers PAC", amount: "$2.6M" },
      { name: "Cargill Inc PAC", amount: "$2.4M" },
      { name: "American Soybean Assn PAC", amount: "$1.8M" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$880K" },
      { name: "John Boozman", party: "R", state: "AR", amount: "$760K" },
      { name: "Debbie Stabenow", party: "D", state: "MI", amount: "$720K" },
      { name: "Chuck Grassley", party: "R", state: "IA", amount: "$680K" },
      { name: "Joni Ernst", party: "R", state: "IA", amount: "$620K" },
    ],
    interestBreakdown: [
      { label: "Farm Subsidies & Crop Insurance", pct: 32 },
      { label: "Trade & Export Policy", pct: 24 },
      { label: "Pesticide & GMO Rules", pct: 18 },
      { label: "Farmworker Immigration", pct: 14 },
      { label: "Antitrust (Agribusiness)", pct: 12 },
    ],
  },
  {
    name: "Lawyers / Legal Industry / Trial Bar",
    tag: "LEGAL",
    acronym: "ABA",
    description: "The legal sector — trial lawyers, law firms, and the American Bar Association — spends $75–$140M annually. Trial lawyers are predominantly Democratic donors who fund campaigns to preserve class actions, jury trials, and tort liability. Large law firms donate to both parties. The sector opposes tort reform, mandatory arbitration clauses, and caps on punitive damages.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$75M–$140M",
    partySplitDem: 68,
    partySplitRep: 32,
    website: "https://www.americanbar.org",
    headquarters: "Chicago, IL",
    industry: "legal",
    influenceScore: 5,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=K",
    topPacs: [
      { name: "Association of Trial Lawyers PAC", amount: "$8.4M" },
      { name: "Skadden Arps et al PAC", amount: "$3.2M" },
      { name: "Kirkland & Ellis PAC", amount: "$2.8M" },
      { name: "Latham & Watkins PAC", amount: "$2.4M" },
      { name: "Jones Day PAC", amount: "$1.9M" },
    ],
    topCandidates: [
      { name: "Chuck Schumer", party: "D", state: "NY", amount: "$920K" },
      { name: "Dick Durbin", party: "D", state: "IL", amount: "$840K" },
      { name: "Amy Klobuchar", party: "D", state: "MN", amount: "$760K" },
      { name: "Sheldon Whitehouse", party: "D", state: "RI", amount: "$680K" },
      { name: "Tom Cotton", party: "R", state: "AR", amount: "$520K" },
    ],
    interestBreakdown: [
      { label: "Tort & Liability Reform", pct: 35 },
      { label: "Class Action Rules", pct: 25 },
      { label: "Arbitration Mandates", pct: 20 },
      { label: "Judicial Appointments", pct: 12 },
      { label: "Access to Courts", pct: 8 },
    ],
  },
  {
    name: "Labor Unions",
    tag: "LABOR",
    acronym: "AFL-CIO",
    description: "Labor unions spend $70–$140M annually on lobbying and campaign contributions, overwhelmingly to Democrats. The AFL-CIO, SEIU, and teachers unions are the most powerful voices for workers' rights, minimum wage increases, collective bargaining protections, and workplace safety. Union political power has declined as private-sector membership has fallen, but public-sector unions remain formidable.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$70M–$140M",
    partySplitDem: 88,
    partySplitRep: 12,
    website: "https://aflcio.org",
    headquarters: "Washington, DC",
    industry: "labor",
    influenceScore: 30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=P",
    topPacs: [
      { name: "SEIU PAC", amount: "$14.2M" },
      { name: "AFL-CIO PAC", amount: "$12.8M" },
      { name: "National Education Assn PAC", amount: "$11.4M" },
      { name: "UFCW PAC", amount: "$8.6M" },
      { name: "Teamsters PAC", amount: "$7.2M" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", state: "DE", amount: "$2.1M" },
      { name: "Bernie Sanders", party: "D", state: "VT", amount: "$1.6M" },
      { name: "Patty Murray", party: "D", state: "WA", amount: "$1.2M" },
      { name: "Sherrod Brown", party: "D", state: "OH", amount: "$1.1M" },
      { name: "Bob Casey Jr", party: "D", state: "PA", amount: "$980K" },
    ],
    interestBreakdown: [
      { label: "Collective Bargaining Rights", pct: 30 },
      { label: "Minimum Wage & Benefits", pct: 26 },
      { label: "Workplace Safety (OSHA)", pct: 20 },
      { label: "Pension & Retirement Security", pct: 14 },
      { label: "Trade & Outsourcing", pct: 10 },
    ],
  },
  {
    name: "Education / Universities / Student Loans",
    tag: "EDUCATION",
    acronym: "ACE",
    description: "Education lobbying — universities, for-profit schools, and student loan servicers — spends $65–$125M annually. The sector is internally divided: public universities lobby for Pell Grant increases and research funding, while for-profit colleges oppose accountability measures, and student loan servicers fight debt relief programs. Navient and Sallie Mae have long opposed income-based repayment expansion.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$65M–$125M",
    partySplitDem: 65,
    partySplitRep: 35,
    website: "https://www.acenet.edu",
    headquarters: "Washington, DC",
    industry: "education",
    influenceScore: -5,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=W04",
    topPacs: [
      { name: "Navient Corp PAC", amount: "$3.4M" },
      { name: "University of Phoenix PAC", amount: "$2.8M" },
      { name: "Apollo Global (For-Profit Ed)", amount: "$2.2M" },
      { name: "DeVry Education Group PAC", amount: "$1.8M" },
      { name: "Assn of American Universities", amount: "$1.4M" },
    ],
    topCandidates: [
      { name: "Patty Murray", party: "D", state: "WA", amount: "$680K" },
      { name: "Lamar Alexander", party: "R", state: "TN", amount: "$620K" },
      { name: "Bobby Scott", party: "D", state: "VA", amount: "$560K" },
      { name: "Virginia Foxx", party: "R", state: "NC", amount: "$520K" },
      { name: "Richard Durbin", party: "D", state: "IL", amount: "$480K" },
    ],
    interestBreakdown: [
      { label: "Student Loan Policy", pct: 30 },
      { label: "Pell Grants & Federal Aid", pct: 25 },
      { label: "For-Profit College Regulation", pct: 20 },
      { label: "Research Funding", pct: 15 },
      { label: "Higher Ed Accreditation", pct: 10 },
    ],
  },
  {
    name: "Private Equity / Hedge Funds / Venture Capital",
    tag: "PRIVATE_EQUITY",
    acronym: "ILPA",
    description: "Private equity, hedge funds, and venture capital firms spend $60–$125M annually, primarily to protect the carried interest loophole — which allows their profits to be taxed at capital gains rates rather than income rates — and to oppose regulation of leveraged buyouts and short selling. The sector has fought every attempt to close this tax provision for over two decades.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$60M–$125M",
    partySplitDem: 38,
    partySplitRep: 62,
    website: "https://ilpa.org",
    headquarters: "Washington, DC",
    industry: "finance",
    influenceScore: -32,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=F2700",
    topPacs: [
      { name: "Blackstone Group PAC", amount: "$6.8M" },
      { name: "Apollo Global Mgmt PAC", amount: "$5.4M" },
      { name: "KKR & Co PAC", amount: "$4.2M" },
      { name: "Carlyle Group PAC", amount: "$3.8M" },
      { name: "Citadel LLC PAC", amount: "$3.4M" },
    ],
    topCandidates: [
      { name: "Chuck Schumer", party: "D", state: "NY", amount: "$1.2M" },
      { name: "Kyrsten Sinema", party: "D", state: "AZ", amount: "$980K" },
      { name: "Tom Suozzi", party: "D", state: "NY", amount: "$840K" },
      { name: "Mark Warner", party: "D", state: "VA", amount: "$720K" },
      { name: "Marco Rubio", party: "R", state: "FL", amount: "$680K" },
    ],
    interestBreakdown: [
      { label: "Carried Interest Tax Loophole", pct: 38 },
      { label: "Leverage & LBO Regulation", pct: 22 },
      { label: "SEC Disclosure Rules", pct: 18 },
      { label: "Pension Fund Access", pct: 12 },
      { label: "Antitrust & Mergers", pct: 10 },
    ],
  },
  {
    name: "Construction / Contractors / Infrastructure",
    tag: "CONSTRUCTION",
    acronym: "AGC",
    description: "The construction industry and federal contractors spend $60–$120M annually, lobbying for infrastructure spending, project labor agreements, OSHA exemptions, and favorable procurement rules. Defense contractors within this space overlap with the aerospace sector. The industry is bipartisan due to the universal desire for infrastructure investment, but opposes prevailing wage requirements and union mandates.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$60M–$120M",
    partySplitDem: 38,
    partySplitRep: 62,
    website: "https://www.agc.org",
    headquarters: "Arlington, VA",
    industry: "construction",
    influenceScore: -8,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=C",
    topPacs: [
      { name: "Associated General Contractors PAC", amount: "$3.8M" },
      { name: "AECOM Technology PAC", amount: "$2.6M" },
      { name: "Bechtel Group PAC", amount: "$2.2M" },
      { name: "Turner Construction PAC", amount: "$1.8M" },
      { name: "Jacobs Engineering PAC", amount: "$1.6M" },
    ],
    topCandidates: [
      { name: "Peter DeFazio", party: "D", state: "OR", amount: "$640K" },
      { name: "Sam Graves", party: "R", state: "MO", amount: "$580K" },
      { name: "Garret Graves", party: "R", state: "LA", amount: "$520K" },
      { name: "Don Young", party: "R", state: "AK", amount: "$480K" },
      { name: "Rick Larsen", party: "D", state: "WA", amount: "$440K" },
    ],
    interestBreakdown: [
      { label: "Infrastructure Spending", pct: 32 },
      { label: "Federal Contracting Rules", pct: 26 },
      { label: "Prevailing Wage (Davis-Bacon)", pct: 20 },
      { label: "OSHA Safety Standards", pct: 12 },
      { label: "Environmental Permitting", pct: 10 },
    ],
  },
  {
    name: "Food & Beverage",
    tag: "FOOD_BEV",
    acronym: "GMA",
    description: "Food and beverage companies spend $55–$110M annually to oppose nutritional labeling mandates, GMO disclosure requirements, sugar taxes, and school nutrition standards. Companies like PepsiCo, Coca-Cola, Nestlé, and Kraft Heinz collectively fight regulations that would require transparency about ingredients or limit marketing to children. The industry donated heavily to defeat state-level GMO labeling initiatives.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$55M–$110M",
    partySplitDem: 42,
    partySplitRep: 58,
    website: "https://www.grocerymanufacturers.org",
    headquarters: "Washington, DC",
    industry: "food",
    influenceScore: -20,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=G2300",
    topPacs: [
      { name: "PepsiCo Inc PAC", amount: "$3.2M" },
      { name: "Coca-Cola Co PAC", amount: "$2.8M" },
      { name: "Kraft Heinz PAC", amount: "$2.4M" },
      { name: "Tyson Foods PAC", amount: "$2.1M" },
      { name: "Nestle USA PAC", amount: "$1.8M" },
    ],
    topCandidates: [
      { name: "John Boozman", party: "R", state: "AR", amount: "$580K" },
      { name: "Debbie Stabenow", party: "D", state: "MI", amount: "$520K" },
      { name: "Collin Peterson", party: "D", state: "MN", amount: "$480K" },
      { name: "K. Michael Conaway", party: "R", state: "TX", amount: "$440K" },
      { name: "Austin Scott", party: "R", state: "GA", amount: "$400K" },
    ],
    interestBreakdown: [
      { label: "Nutrition Labeling", pct: 30 },
      { label: "School Nutrition Standards", pct: 24 },
      { label: "GMO Disclosure Rules", pct: 20 },
      { label: "Sugar & Soda Taxes", pct: 16 },
      { label: "Food Safety (FDA/USDA)", pct: 10 },
    ],
  },
  {
    name: "Retail / Big Box / E-Commerce",
    tag: "RETAIL",
    acronym: "NRF",
    description: "Retail giants and e-commerce platforms spend $50–$100M annually opposing online sales tax requirements, worker scheduling laws, minimum wage mandates, and consumer protection regulations. Amazon dominates this space, lobbying on labor classification, antitrust, and logistics rules. The National Retail Federation opposes unionization efforts and fights occupational health regulations.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$50M–$100M",
    partySplitDem: 40,
    partySplitRep: 60,
    website: "https://nrf.com",
    headquarters: "Washington, DC",
    industry: "retail",
    influenceScore: -18,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=G4400",
    topPacs: [
      { name: "Amazon.com Inc PAC", amount: "$6.4M" },
      { name: "Walmart Inc PAC", amount: "$4.2M" },
      { name: "Target Corp PAC", amount: "$2.8M" },
      { name: "Home Depot PAC", amount: "$2.4M" },
      { name: "Costco Wholesale PAC", amount: "$1.9M" },
    ],
    topCandidates: [
      { name: "Kevin McCarthy", party: "R", state: "CA", amount: "$680K" },
      { name: "Steny Hoyer", party: "D", state: "MD", amount: "$580K" },
      { name: "Cathy McMorris Rodgers", party: "R", state: "WA", amount: "$520K" },
      { name: "Maria Cantwell", party: "D", state: "WA", amount: "$480K" },
      { name: "Richard Burr", party: "R", state: "NC", amount: "$440K" },
    ],
    interestBreakdown: [
      { label: "Labor & Minimum Wage", pct: 28 },
      { label: "Online Sales Tax", pct: 24 },
      { label: "Antitrust & Marketplace Rules", pct: 22 },
      { label: "Consumer Protection", pct: 16 },
      { label: "Supply Chain & Trade", pct: 10 },
    ],
  },
  {
    name: "Renewable Energy / Solar / Wind / Batteries",
    tag: "RENEWABLE_ENERGY",
    acronym: "SEIA",
    description: "The renewable energy sector — solar, wind, battery storage, and clean tech — has grown to spend $50–$100M annually as it fights for production tax credits, investment tax credits, and federal renewable energy mandates. The sector navigates between Democratic enthusiasm and Republican skepticism, lobbying to protect IRA clean energy incentives from repeal while expanding grid interconnection access.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$50M–$100M",
    partySplitDem: 72,
    partySplitRep: 28,
    website: "https://www.seia.org",
    headquarters: "Washington, DC",
    industry: "energy",
    influenceScore: 25,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=E1500",
    topPacs: [
      { name: "NextEra Energy PAC (Renewables)", amount: "$4.8M" },
      { name: "First Solar Inc PAC", amount: "$2.4M" },
      { name: "Orsted North America PAC", amount: "$1.8M" },
      { name: "American Clean Power Assn", amount: "$1.6M" },
      { name: "Tesla Inc PAC", amount: "$1.4M" },
    ],
    topCandidates: [
      { name: "Joe Manchin", party: "D", state: "WV", amount: "$740K" },
      { name: "Jon Tester", party: "D", state: "MT", amount: "$620K" },
      { name: "Debbie Stabenow", party: "D", state: "MI", amount: "$580K" },
      { name: "Lisa Murkowski", party: "R", state: "AK", amount: "$480K" },
      { name: "Ron Wyden", party: "D", state: "OR", amount: "$460K" },
    ],
    interestBreakdown: [
      { label: "Production & Investment Tax Credits", pct: 35 },
      { label: "Grid Access & Interconnection", pct: 25 },
      { label: "EV & Battery Policy", pct: 20 },
      { label: "Permitting Reform", pct: 12 },
      { label: "Offshore Wind Development", pct: 8 },
    ],
  },
  {
    name: "Crypto / Blockchain / Fintech",
    tag: "CRYPTO",
    acronym: "DCA",
    description: "The cryptocurrency and blockchain sector has rapidly expanded its lobbying from nearly zero in 2018 to $40–$100M+ today. It fights SEC oversight, IRS reporting requirements, and banking regulations that would constrain crypto. Following a wave of fraud and exchange collapses (FTX), the industry has spent heavily to prevent strict regulation while seeking regulatory clarity that legitimizes its activities.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$40M–$100M+",
    partySplitDem: 44,
    partySplitRep: 56,
    website: "https://digitalchamber.org",
    headquarters: "Washington, DC",
    industry: "crypto",
    influenceScore: -15,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=B1200",
    topPacs: [
      { name: "Fairshake (Crypto Super PAC)", amount: "$18.6M" },
      { name: "Coinbase Global PAC", amount: "$4.8M" },
      { name: "Ripple Labs PAC", amount: "$3.2M" },
      { name: "Andreessen Horowitz (a16z)", amount: "$2.8M" },
      { name: "Kraken Exchange PAC", amount: "$1.9M" },
    ],
    topCandidates: [
      { name: "Patrick McHenry", party: "R", state: "NC", amount: "$840K" },
      { name: "Ritchie Torres", party: "D", state: "NY", amount: "$720K" },
      { name: "Cynthia Lummis", party: "R", state: "WY", amount: "$680K" },
      { name: "Kirsten Gillibrand", party: "D", state: "NY", amount: "$580K" },
      { name: "Tom Emmer", party: "R", state: "MN", amount: "$520K" },
    ],
    interestBreakdown: [
      { label: "SEC & CFTC Regulation", pct: 32 },
      { label: "IRS Reporting Rules", pct: 24 },
      { label: "Banking & Custody Access", pct: 22 },
      { label: "Stablecoin Legislation", pct: 14 },
      { label: "AML & Compliance", pct: 8 },
    ],
  },
  {
    name: "AI / Data Centers / Automation",
    tag: "AI_TECH",
    acronym: "CCIA",
    description: "The artificial intelligence and data center sector has emerged as a major lobbying force, spending $40–$100M+ annually. Companies like Microsoft, Google, and OpenAI lobby to shape AI regulations favorably, secure federal AI contracts, and resist liability frameworks for algorithmic harms. The sector also lobbies on energy policy as data centers consume massive electricity, and on immigration for AI talent.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$40M–$100M+",
    partySplitDem: 58,
    partySplitRep: 42,
    website: "https://www.ccia.org",
    headquarters: "Washington, DC",
    industry: "ai_tech",
    influenceScore: -8,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=B12",
    topPacs: [
      { name: "Microsoft Corp PAC (AI)", amount: "$5.2M" },
      { name: "Google / DeepMind PAC", amount: "$4.8M" },
      { name: "Meta AI PAC", amount: "$3.6M" },
      { name: "Nvidia Corp PAC", amount: "$3.2M" },
      { name: "OpenAI / Anthropic (advocacy)", amount: "$2.1M" },
    ],
    topCandidates: [
      { name: "Maria Cantwell", party: "D", state: "WA", amount: "$720K" },
      { name: "Ted Cruz", party: "R", state: "TX", amount: "$580K" },
      { name: "Amy Klobuchar", party: "D", state: "MN", amount: "$540K" },
      { name: "John Thune", party: "R", state: "SD", amount: "$480K" },
      { name: "Ro Khanna", party: "D", state: "CA", amount: "$460K" },
    ],
    interestBreakdown: [
      { label: "AI Safety & Liability", pct: 28 },
      { label: "Data Center Energy Policy", pct: 24 },
      { label: "Government AI Contracts", pct: 22 },
      { label: "Immigration (H-1B / AI Talent)", pct: 16 },
      { label: "Export Controls (AI Chips)", pct: 10 },
    ],
  },
  {
    name: "Media / Entertainment / Streaming",
    tag: "MEDIA",
    acronym: "MPA",
    description: "The media, entertainment, and streaming sector spends $40–$90M annually on lobbying related to copyright enforcement, content regulation, antitrust policy, and Section 230 protections. Hollywood studios, streaming giants like Netflix and Disney, and news organizations lobby on intellectual property, LGBTQ+ content protections, and spectrum policy. The sector overwhelmingly supports Democrats.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$40M–$90M",
    partySplitDem: 70,
    partySplitRep: 30,
    website: "https://www.motionpictures.org",
    headquarters: "Los Angeles, CA",
    industry: "media",
    influenceScore: 5,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=B02",
    topPacs: [
      { name: "Walt Disney Co PAC", amount: "$3.8M" },
      { name: "Comcast/NBCUniversal PAC", amount: "$3.4M" },
      { name: "Netflix Inc PAC", amount: "$2.2M" },
      { name: "Warner Bros Discovery PAC", amount: "$2.0M" },
      { name: "Spotify PAC", amount: "$1.4M" },
    ],
    topCandidates: [
      { name: "Adam Schiff", party: "D", state: "CA", amount: "$680K" },
      { name: "Ted Lieu", party: "D", state: "CA", amount: "$580K" },
      { name: "Darrell Issa", party: "R", state: "CA", amount: "$440K" },
      { name: "Hakeem Jeffries", party: "D", state: "NY", amount: "$420K" },
      { name: "Anna Eshoo", party: "D", state: "CA", amount: "$400K" },
    ],
    interestBreakdown: [
      { label: "Copyright & IP Enforcement", pct: 32 },
      { label: "Section 230 Protections", pct: 24 },
      { label: "Antitrust (Streaming Mergers)", pct: 20 },
      { label: "Spectrum & Broadcast Policy", pct: 14 },
      { label: "Content Rating Regulation", pct: 10 },
    ],
  },
  {
    name: "Alcohol / Beer / Wine / Spirits",
    tag: "ALCOHOL",
    acronym: "DISCUS",
    description: "The alcohol industry spends $35–$80M annually lobbying against excise tax increases, advertising restrictions, and state distribution regulations. Beer, wine, and spirits companies lobby on three-tier distribution laws, Sunday sale rules, direct-to-consumer shipping, and drunk driving penalties. The industry is broadly bipartisan due to its geographic diversity.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$35M–$80M",
    partySplitDem: 48,
    partySplitRep: 52,
    website: "https://www.distilledspirits.org",
    headquarters: "Washington, DC",
    industry: "alcohol",
    influenceScore: -10,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=G2600",
    topPacs: [
      { name: "Anheuser-Busch InBev PAC", amount: "$2.8M" },
      { name: "Brown-Forman Corp PAC", amount: "$1.9M" },
      { name: "Molson Coors PAC", amount: "$1.6M" },
      { name: "Wine Institute PAC", amount: "$1.2M" },
      { name: "National Beer Wholesalers PAC", amount: "$3.4M" },
    ],
    topCandidates: [
      { name: "Roy Blunt", party: "R", state: "MO", amount: "$480K" },
      { name: "Jim Cooper", party: "D", state: "TN", amount: "$420K" },
      { name: "Patrick Leahy", party: "D", state: "VT", amount: "$380K" },
      { name: "Kevin Brady", party: "R", state: "TX", amount: "$360K" },
      { name: "Richard Neal", party: "D", state: "MA", amount: "$340K" },
    ],
    interestBreakdown: [
      { label: "Excise Tax Policy", pct: 30 },
      { label: "Distribution & Three-Tier Law", pct: 26 },
      { label: "Direct-to-Consumer Shipping", pct: 20 },
      { label: "Advertising Restrictions", pct: 14 },
      { label: "DUI & Liability Rules", pct: 10 },
    ],
  },
  {
    name: "Tobacco / Vaping / Nicotine",
    tag: "TOBACCO",
    acronym: "RJR",
    description: "Tobacco and nicotine product companies spend $30–$75M annually fighting FDA regulation, flavor bans, menthol cigarette prohibitions, and vaping restrictions. Altria (formerly Philip Morris), Reynolds American, and JUUL Labs collectively lobby to protect one of the most profitable — and deadly — industries in history. The sector also targets youth-access regulations while simultaneously fighting restrictions on marketing.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$30M–$75M",
    partySplitDem: 30,
    partySplitRep: 70,
    website: "https://www.altria.com",
    headquarters: "Richmond, VA",
    industry: "tobacco",
    influenceScore: -40,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=A12",
    topPacs: [
      { name: "Altria Group (Philip Morris) PAC", amount: "$5.2M" },
      { name: "Reynolds American PAC", amount: "$3.8M" },
      { name: "JUUL Labs PAC", amount: "$2.4M" },
      { name: "Lorillard Inc PAC", amount: "$1.8M" },
      { name: "Vector Group (Liggett) PAC", amount: "$1.2M" },
    ],
    topCandidates: [
      { name: "Richard Burr", party: "R", state: "NC", amount: "$680K" },
      { name: "Thom Tillis", party: "R", state: "NC", amount: "$580K" },
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$520K" },
      { name: "Roy Blunt", party: "R", state: "MO", amount: "$460K" },
      { name: "Tom Cole", party: "R", state: "OK", amount: "$420K" },
    ],
    interestBreakdown: [
      { label: "FDA Tobacco Regulation", pct: 35 },
      { label: "Menthol & Flavor Bans", pct: 25 },
      { label: "Vaping & E-Cigarette Rules", pct: 20 },
      { label: "Marketing Restrictions", pct: 12 },
      { label: "Excise & Sales Tax", pct: 8 },
    ],
  },
  {
    name: "Gambling / Casinos / Sports Betting",
    tag: "GAMBLING",
    acronym: "AGA",
    description: "The gambling industry — casinos, online gaming, and sports betting — spends $30–$75M annually lobbying for state-level legalization, favorable tax treatment, and opposition to problem gambling regulations. Since the Supreme Court's 2018 PASPA ruling, sports betting has expanded to 38+ states, generating a lobbying frenzy. Tribal gaming interests operate separately and often in opposition to commercial casinos.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$30M–$75M",
    partySplitDem: 46,
    partySplitRep: 54,
    website: "https://www.americangaming.org",
    headquarters: "Washington, DC",
    industry: "gambling",
    influenceScore: -12,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=G5500",
    topPacs: [
      { name: "MGM Resorts International PAC", amount: "$2.8M" },
      { name: "Las Vegas Sands Corp PAC", amount: "$2.4M" },
      { name: "DraftKings Inc PAC", amount: "$1.9M" },
      { name: "FanDuel (Flutter) PAC", amount: "$1.8M" },
      { name: "Caesars Entertainment PAC", amount: "$1.6M" },
    ],
    topCandidates: [
      { name: "Jacky Rosen", party: "D", state: "NV", amount: "$480K" },
      { name: "Catherine Cortez Masto", party: "D", state: "NV", amount: "$420K" },
      { name: "Mark Amodei", party: "R", state: "NV", amount: "$380K" },
      { name: "Dina Titus", party: "D", state: "NV", amount: "$360K" },
      { name: "Frank LoBiondo", party: "R", state: "NJ", amount: "$320K" },
    ],
    interestBreakdown: [
      { label: "Sports Betting Regulation", pct: 32 },
      { label: "Online Gaming Licensing", pct: 26 },
      { label: "Casino Tax Policy", pct: 20 },
      { label: "Problem Gambling Rules", pct: 12 },
      { label: "Tribal Gaming Compacts", pct: 10 },
    ],
  },
  {
    name: "Gun Rights",
    tag: "GUN_RIGHTS",
    acronym: "NRA",
    description: "Gun rights organizations spend $25–$70M annually to protect the Second Amendment, oppose background check expansions, resist assault weapons bans, and fight red flag laws. The NRA and Gun Owners of America are the dominant voices, though the NRA has weakened after bankruptcy proceedings and internal scandals. The sector is almost exclusively Republican-aligned and has successfully blocked federal gun legislation for decades.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$25M–$70M",
    partySplitDem: 5,
    partySplitRep: 95,
    website: "https://home.nra.org",
    headquarters: "Fairfax, VA",
    industry: "firearms",
    influenceScore: -38,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q13",
    topPacs: [
      { name: "NRA Political Victory Fund", amount: "$14.4M" },
      { name: "Gun Owners of America PAC", amount: "$4.2M" },
      { name: "National Shooting Sports Found.", amount: "$2.8M" },
      { name: "Safari Club International PAC", amount: "$1.4M" },
      { name: "NRA-ILA (lobbying arm)", amount: "$8.6M" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", state: "FL", amount: "$2.1M" },
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$1.4M" },
      { name: "Richard Burr", party: "R", state: "NC", amount: "$1.1M" },
      { name: "Roy Blunt", party: "R", state: "MO", amount: "$980K" },
      { name: "Tom Tillis", party: "R", state: "NC", amount: "$860K" },
    ],
    interestBreakdown: [
      { label: "Background Check Legislation", pct: 30 },
      { label: "Assault Weapons & Magazine Bans", pct: 26 },
      { label: "Red Flag / ERPO Laws", pct: 22 },
      { label: "Concealed Carry Laws", pct: 14 },
      { label: "Gun Manufacturer Liability", pct: 8 },
    ],
  },
  {
    name: "Gun Control",
    tag: "GUN_CONTROL",
    acronym: "Everytown",
    description: "Gun control and gun safety organizations have grown dramatically since Sandy Hook, now spending $25–$70M annually. Everytown for Gun Safety (funded by Michael Bloomberg), Giffords, and Moms Demand Action lobby for universal background checks, red flag laws, assault weapons restrictions, and ghost gun regulations. The sector is almost exclusively Democrat-aligned.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$25M–$70M",
    partySplitDem: 96,
    partySplitRep: 4,
    website: "https://everytown.org",
    headquarters: "New York, NY",
    industry: "gun_control",
    influenceScore: 28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q14",
    topPacs: [
      { name: "Everytown for Gun Safety PAC", amount: "$12.8M" },
      { name: "Giffords PAC", amount: "$4.6M" },
      { name: "Moms Demand Action (advocacy)", amount: "$3.2M" },
      { name: "March for Our Lives", amount: "$1.8M" },
      { name: "Brady Campaign PAC", amount: "$1.4M" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", state: "DE", amount: "$1.6M" },
      { name: "Gabrielle Giffords", party: "D", state: "AZ", amount: "$1.1M" },
      { name: "Beto O'Rourke", party: "D", state: "TX", amount: "$940K" },
      { name: "Chris Murphy", party: "D", state: "CT", amount: "$820K" },
      { name: "Jacky Rosen", party: "D", state: "NV", amount: "$680K" },
    ],
    interestBreakdown: [
      { label: "Universal Background Checks", pct: 32 },
      { label: "Red Flag / ERPO Laws", pct: 26 },
      { label: "Assault Weapons Restrictions", pct: 22 },
      { label: "Ghost Gun Regulation", pct: 12 },
      { label: "Safe Storage Requirements", pct: 8 },
    ],
  },
  {
    name: "Environmental / Climate Advocacy",
    tag: "ENVIRONMENT",
    acronym: "LCV",
    description: "Environmental and climate advocacy groups spend $25–$70M annually lobbying for clean energy standards, carbon pricing, emissions regulations, and public lands protection. The League of Conservation Voters, Sierra Club, and Environmental Defense Fund are major players. The sector has grown significantly as climate urgency has increased, though it remains vastly outspent by the fossil fuel industry.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$25M–$70M",
    partySplitDem: 92,
    partySplitRep: 8,
    website: "https://www.lcv.org",
    headquarters: "Washington, DC",
    industry: "environment",
    influenceScore: 38,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q11",
    topPacs: [
      { name: "League of Conservation Voters PAC", amount: "$8.4M" },
      { name: "Sierra Club PAC", amount: "$6.2M" },
      { name: "Environmental Defense Action Fund", amount: "$4.8M" },
      { name: "NextGen Climate PAC", amount: "$4.2M" },
      { name: "Natural Resources Defense Council", amount: "$2.6M" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", state: "DE", amount: "$1.4M" },
      { name: "Bernie Sanders", party: "D", state: "VT", amount: "$1.1M" },
      { name: "Alexandria Ocasio-Cortez", party: "D", state: "NY", amount: "$940K" },
      { name: "Ed Markey", party: "D", state: "MA", amount: "$820K" },
      { name: "Ron Wyden", party: "D", state: "OR", amount: "$720K" },
    ],
    interestBreakdown: [
      { label: "Clean Energy Mandates", pct: 30 },
      { label: "Carbon Pricing / Tax", pct: 26 },
      { label: "EPA Emissions Rules", pct: 22 },
      { label: "Public Lands Protection", pct: 14 },
      { label: "Water & Air Quality", pct: 8 },
    ],
  },
  {
    name: "Civil Rights / Civil Liberties",
    tag: "CIVIL_RIGHTS",
    acronym: "ACLU",
    description: "Civil rights and civil liberties organizations spend $25–$70M annually on lobbying for voting rights, criminal justice reform, LGBTQ+ equality, immigration rights, and surveillance oversight. The ACLU, NAACP Legal Defense Fund, and Human Rights Campaign are key players. The sector is almost entirely Democratic-aligned and often engages in both legislative lobbying and constitutional litigation.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$25M–$70M",
    partySplitDem: 94,
    partySplitRep: 6,
    website: "https://www.aclu.org",
    headquarters: "New York, NY",
    industry: "civil_rights",
    influenceScore: 36,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q05",
    topPacs: [
      { name: "ACLU Voter Education Fund", amount: "$5.8M" },
      { name: "Human Rights Campaign PAC", amount: "$5.2M" },
      { name: "NAACP LDF Action Fund", amount: "$3.4M" },
      { name: "Color of Change PAC", amount: "$2.8M" },
      { name: "Lambda Legal PAC", amount: "$1.6M" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", state: "DE", amount: "$1.2M" },
      { name: "Cori Bush", party: "D", state: "MO", amount: "$880K" },
      { name: "Ayanna Pressley", party: "D", state: "MA", amount: "$760K" },
      { name: "Rashida Tlaib", party: "D", state: "MI", amount: "$680K" },
      { name: "Hakeem Jeffries", party: "D", state: "NY", amount: "$620K" },
    ],
    interestBreakdown: [
      { label: "Voting Rights & Election Access", pct: 28 },
      { label: "Criminal Justice Reform", pct: 26 },
      { label: "LGBTQ+ Equality", pct: 22 },
      { label: "Surveillance & Privacy", pct: 14 },
      { label: "Immigration Rights", pct: 10 },
    ],
  },
  {
    name: "Pro-Israel / Middle East Advocacy",
    tag: "PRO_ISRAEL",
    acronym: "AIPAC",
    description: "Pro-Israel organizations and Middle East policy advocacy groups spend $25–$70M annually — with AIPAC dramatically expanding its direct electoral spending through affiliated super PACs since 2022. The sector funds both parties but has recently engaged in aggressive primary challenges against progressive Democrats critical of Israeli government policy. It is one of the most influential single-issue lobbying forces in U.S. foreign policy.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$25M–$70M",
    partySplitDem: 50,
    partySplitRep: 50,
    website: "https://www.aipac.org",
    headquarters: "Washington, DC",
    industry: "foreign_policy",
    influenceScore: -22,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q08",
    topPacs: [
      { name: "United Democracy Project (AIPAC)", amount: "$24.6M" },
      { name: "AIPAC PAC", amount: "$6.8M" },
      { name: "Democratic Majority for Israel", amount: "$4.2M" },
      { name: "Republican Jewish Coalition PAC", amount: "$3.8M" },
      { name: "J Street PAC", amount: "$2.4M" },
    ],
    topCandidates: [
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$1.1M" },
      { name: "Chuck Schumer", party: "D", state: "NY", amount: "$980K" },
      { name: "Bob Menendez", party: "D", state: "NJ", amount: "$860K" },
      { name: "Marco Rubio", party: "R", state: "FL", amount: "$820K" },
      { name: "Ben Cardin", party: "D", state: "MD", amount: "$760K" },
    ],
    interestBreakdown: [
      { label: "US-Israel Security Aid", pct: 35 },
      { label: "Iran Nuclear Policy", pct: 25 },
      { label: "Palestinian Authority Policy", pct: 20 },
      { label: "Primary Electoral Challenges", pct: 12 },
      { label: "BDS Movement Opposition", pct: 8 },
    ],
  },
  {
    name: "Foreign Governments / Foreign Policy Interests",
    tag: "FOREIGN_POLICY",
    acronym: "FARA",
    description: "Foreign governments and their interests spend $25–$70M annually on registered lobbyists under FARA (Foreign Agents Registration Act). Saudi Arabia, UAE, Turkey, China-linked interests, and dozens of other governments pay top D.C. firms to influence U.S. policy. Disclosures are required but enforcement is weak. This spending is separate from official embassy activities and covers both lobbying and PR campaigns.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$25M–$70M",
    partySplitDem: 46,
    partySplitRep: 54,
    website: "https://efile.fara.gov",
    headquarters: "Washington, DC",
    industry: "foreign_policy",
    influenceScore: -30,
    dataSourceName: "DOJ FARA Database",
    dataSourceUrl: "https://www.justice.gov/nsd-fara",
    topPacs: [
      { name: "Saudi Arabia (BGR Group)", amount: "$5.4M" },
      { name: "UAE (Brownstein Hyatt)", amount: "$4.8M" },
      { name: "Turkey (Greenberg Traurig)", amount: "$3.2M" },
      { name: "Qatar (Squire Patton Boggs)", amount: "$2.8M" },
      { name: "Israel (lobbying firms)", amount: "$2.4M" },
    ],
    topCandidates: [
      { name: "Bob Menendez", party: "D", state: "NJ", amount: "$860K" },
      { name: "Lindsey Graham", party: "R", state: "SC", amount: "$720K" },
      { name: "Jim Inhofe", party: "R", state: "OK", amount: "$640K" },
      { name: "Chris Coons", party: "D", state: "DE", amount: "$580K" },
      { name: "Jack Reed", party: "D", state: "RI", amount: "$520K" },
    ],
    interestBreakdown: [
      { label: "Arms Sales & Military Aid", pct: 30 },
      { label: "Trade Agreements", pct: 24 },
      { label: "Sanctions Policy", pct: 22 },
      { label: "Diplomatic Relations", pct: 14 },
      { label: "PR & Public Diplomacy", pct: 10 },
    ],
  },
  {
    name: "Senior Citizens / AARP / Retirement Policy",
    tag: "SENIORS",
    acronym: "AARP",
    description: "Senior citizen advocacy — dominated by AARP with 38 million members — spends $25–$65M annually on Social Security, Medicare, prescription drug pricing, and elder care policy. AARP is technically nonpartisan but its policy agenda aligns primarily with Democratic priorities. The senior lobby is one of the most consistently effective due to high voter turnout among its constituency.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$25M–$65M",
    partySplitDem: 60,
    partySplitRep: 40,
    website: "https://www.aarp.org",
    headquarters: "Washington, DC",
    industry: "seniors",
    influenceScore: 20,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/orgs/aarp",
    topPacs: [
      { name: "AARP PAC", amount: "$4.8M" },
      { name: "National Committee to Preserve Social Security", amount: "$2.4M" },
      { name: "Alliance for Retired Americans PAC", amount: "$1.8M" },
      { name: "Senior Citizens League", amount: "$1.2M" },
      { name: "NARFE PAC", amount: "$0.8M" },
    ],
    topCandidates: [
      { name: "Chuck Grassley", party: "R", state: "IA", amount: "$620K" },
      { name: "Ron Wyden", party: "D", state: "OR", amount: "$580K" },
      { name: "Pat Roberts", party: "R", state: "KS", amount: "$520K" },
      { name: "Maxine Waters", party: "D", state: "CA", amount: "$460K" },
      { name: "Richard Shelby", party: "R", state: "AL", amount: "$420K" },
    ],
    interestBreakdown: [
      { label: "Social Security Solvency", pct: 32 },
      { label: "Medicare Benefits", pct: 28 },
      { label: "Prescription Drug Pricing", pct: 22 },
      { label: "Long-Term Care Policy", pct: 10 },
      { label: "Elder Financial Fraud", pct: 8 },
    ],
  },
  {
    name: "Veterans / Military Families",
    tag: "VETERANS",
    acronym: "VFW",
    description: "Veterans organizations spend $20–$60M annually on VA funding, veterans' healthcare, education benefits (GI Bill), disability compensation, and military housing allowances. The VFW, DAV, and American Legion lobby on behalf of veterans in a fully bipartisan manner. Veterans' issues enjoy rare consensus in Congress, making this sector effective at securing consistent funding increases.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$20M–$60M",
    partySplitDem: 52,
    partySplitRep: 48,
    website: "https://www.vfw.org",
    headquarters: "Washington, DC",
    industry: "veterans",
    influenceScore: 22,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q03",
    topPacs: [
      { name: "VFW PAC", amount: "$2.8M" },
      { name: "Disabled American Veterans PAC", amount: "$2.2M" },
      { name: "American Legion PAC", amount: "$1.8M" },
      { name: "AMVETS PAC", amount: "$1.2M" },
      { name: "Student Veterans of America", amount: "$0.8M" },
    ],
    topCandidates: [
      { name: "Jon Tester", party: "D", state: "MT", amount: "$480K" },
      { name: "Johnny Isakson", party: "R", state: "GA", amount: "$420K" },
      { name: "Mike Coffman", party: "R", state: "CO", amount: "$380K" },
      { name: "Mark Takano", party: "D", state: "CA", amount: "$360K" },
      { name: "Jeff Miller", party: "R", state: "FL", amount: "$320K" },
    ],
    interestBreakdown: [
      { label: "VA Healthcare Funding", pct: 32 },
      { label: "Disability Benefits", pct: 26 },
      { label: "GI Bill & Education", pct: 22 },
      { label: "Veterans Housing & Homelessness", pct: 12 },
      { label: "Military Family Support", pct: 8 },
    ],
  },
  {
    name: "Police / Law Enforcement / Prosecutors",
    tag: "POLICE",
    acronym: "FOP",
    description: "Police associations and prosecutor organizations spend $20–$60M annually opposing criminal justice reform, qualified immunity reform, and civilian oversight. The Fraternal Order of Police and National District Attorneys Association lobby to maintain broad police power, oppose sentencing reforms, and secure increased law enforcement funding. The sector is Republican-aligned but has bipartisan support in many moderate jurisdictions.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$20M–$60M",
    partySplitDem: 35,
    partySplitRep: 65,
    website: "https://www.fop.net",
    headquarters: "Washington, DC",
    industry: "law_enforcement",
    influenceScore: -12,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q15",
    topPacs: [
      { name: "Fraternal Order of Police PAC", amount: "$3.4M" },
      { name: "National Sheriffs Assn PAC", amount: "$1.8M" },
      { name: "International Assn of Chiefs of Police", amount: "$1.4M" },
      { name: "National Dist Attorneys Assn", amount: "$1.2M" },
      { name: "Police Officers Research Assn", amount: "$0.8M" },
    ],
    topCandidates: [
      { name: "Donald Trump", party: "R", state: "FL", amount: "$680K" },
      { name: "Tom Cotton", party: "R", state: "AR", amount: "$520K" },
      { name: "Bill Barr (support)", amount: "—", party: "R", state: "DC" },
      { name: "John Cornyn", party: "R", state: "TX", amount: "$460K" },
      { name: "David Clarke (advocacy)", party: "R", state: "WI", amount: "$380K" },
    ],
    interestBreakdown: [
      { label: "Qualified Immunity Protection", pct: 28 },
      { label: "Police Funding & Equipment", pct: 26 },
      { label: "Sentencing & Bail Reform", pct: 22 },
      { label: "Civilian Oversight Opposition", pct: 14 },
      { label: "Gang & Drug Enforcement", pct: 10 },
    ],
  },
  {
    name: "Corrections / Private Prisons",
    tag: "PRISONS",
    acronym: "GEO",
    description: "The private prison and corrections industry spends $15–$50M annually lobbying for mandatory minimum sentences, immigration detention contracts, and against sentencing reform and alternatives to incarceration. GEO Group and CoreCivic (formerly CCA) are the dominant companies. They profit from incarceration and have a direct financial interest in policies that keep more Americans — and immigrants — locked up.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$15M–$50M",
    partySplitDem: 20,
    partySplitRep: 80,
    website: "https://www.geogroup.com",
    headquarters: "Boca Raton, FL",
    industry: "corrections",
    influenceScore: -42,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=G8600",
    topPacs: [
      { name: "GEO Group PAC", amount: "$2.8M" },
      { name: "CoreCivic Inc PAC", amount: "$2.4M" },
      { name: "Management & Training Corp PAC", amount: "$1.2M" },
      { name: "LaSalle Corrections PAC", amount: "$0.8M" },
      { name: "Securus Technologies PAC", amount: "$0.6M" },
    ],
    topCandidates: [
      { name: "Tom Cotton", party: "R", state: "AR", amount: "$480K" },
      { name: "Marco Rubio", party: "R", state: "FL", amount: "$420K" },
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$380K" },
      { name: "John Cornyn", party: "R", state: "TX", amount: "$340K" },
      { name: "Ron DeSantis", party: "R", state: "FL", amount: "$310K" },
    ],
    interestBreakdown: [
      { label: "Immigration Detention Contracts", pct: 35 },
      { label: "Mandatory Minimum Sentences", pct: 28 },
      { label: "Prison Privatization", pct: 22 },
      { label: "Sentencing Reform Opposition", pct: 10 },
      { label: "Electronic Monitoring", pct: 5 },
    ],
  },
  {
    name: "Religious / Faith-Based Advocacy",
    tag: "RELIGIOUS",
    acronym: "USCCB",
    description: "Religious organizations and faith-based advocacy groups spend $15–$50M annually on a wide range of issues from abortion and LGBTQ+ rights to immigration and poverty relief. Catholic, evangelical, and other faith groups lobby on school prayer, religious exemptions from anti-discrimination laws, abortion restrictions, and social welfare funding. The sector spans both parties depending on issue.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$15M–$50M",
    partySplitDem: 38,
    partySplitRep: 62,
    website: "https://www.usccb.org",
    headquarters: "Washington, DC",
    industry: "religious",
    influenceScore: -8,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q09",
    topPacs: [
      { name: "National Right to Life PAC", amount: "$3.2M" },
      { name: "Focus on the Family Action", amount: "$2.4M" },
      { name: "USCCB (policy advocacy)", amount: "$1.8M" },
      { name: "Family Research Council Action", amount: "$1.6M" },
      { name: "Faith & Freedom Coalition", amount: "$1.4M" },
    ],
    topCandidates: [
      { name: "Mike Pence", party: "R", state: "IN", amount: "$620K" },
      { name: "Ted Cruz", party: "R", state: "TX", amount: "$580K" },
      { name: "Marco Rubio", party: "R", state: "FL", amount: "$520K" },
      { name: "Kevin McCarthy", party: "R", state: "CA", amount: "$440K" },
      { name: "Nancy Pelosi", party: "D", state: "CA", amount: "$380K" },
    ],
    interestBreakdown: [
      { label: "Abortion & Reproductive Rights", pct: 32 },
      { label: "Religious Liberty Exemptions", pct: 26 },
      { label: "LGBTQ+ Anti-Discrimination", pct: 20 },
      { label: "School Prayer & Vouchers", pct: 14 },
      { label: "Immigration & Refugee Policy", pct: 8 },
    ],
  },
  {
    name: "Immigration Advocacy / Border Policy",
    tag: "IMMIGRATION",
    acronym: "NILC",
    description: "Immigration advocacy spans both sides: pro-immigration groups lobby for DACA protection, pathways to citizenship, asylum reform, and H-1B expansion, while restrictionist groups push for stricter enforcement, wall funding, and reduced legal immigration. The sector spends $15–$45M annually. Business interests (tech, agriculture) often align with pro-immigration groups while nativist organizations align with restrictionist Republicans.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$15M–$45M",
    partySplitDem: 60,
    partySplitRep: 40,
    website: "https://www.nilc.org",
    headquarters: "Los Angeles, CA",
    industry: "immigration",
    influenceScore: 8,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q16",
    topPacs: [
      { name: "FWD.us (tech-backed immigration)", amount: "$4.2M" },
      { name: "National Immigration Law Center", amount: "$2.8M" },
      { name: "Federation for American Immigration Reform", amount: "$2.4M" },
      { name: "NumbersUSA PAC", amount: "$1.8M" },
      { name: "United We Dream Action", amount: "$1.2M" },
    ],
    topCandidates: [
      { name: "Dick Durbin", party: "D", state: "IL", amount: "$580K" },
      { name: "Lindsey Graham", party: "R", state: "SC", amount: "$480K" },
      { name: "Marco Rubio", party: "R", state: "FL", amount: "$440K" },
      { name: "Tom Cotton", party: "R", state: "AR", amount: "$400K" },
      { name: "Zoe Lofgren", party: "D", state: "CA", amount: "$380K" },
    ],
    interestBreakdown: [
      { label: "DACA & Dreamers", pct: 28 },
      { label: "Border Enforcement & Wall", pct: 26 },
      { label: "Asylum & Refugee Policy", pct: 22 },
      { label: "H-1B & Work Visas", pct: 14 },
      { label: "Pathway to Citizenship", pct: 10 },
    ],
  },
  {
    name: "Consumer Protection / Public Interest",
    tag: "CONSUMER_PROTECT",
    acronym: "PIRG",
    description: "Consumer protection and public interest organizations spend $15–$45M annually advocating for CFPB enforcement, product safety, data privacy, price transparency, and anti-monopoly action. Groups like Public Citizen, U.S. PIRG, and Consumer Reports are the primary voices. They are systematically outspent by the industries they challenge but have achieved landmark protections through strategic legislation and litigation.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$15M–$45M",
    partySplitDem: 90,
    partySplitRep: 10,
    website: "https://pirg.org",
    headquarters: "Washington, DC",
    industry: "consumer_protection",
    influenceScore: 35,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q07",
    topPacs: [
      { name: "Public Citizen Action", amount: "$1.8M" },
      { name: "U.S. PIRG Action Fund", amount: "$1.4M" },
      { name: "Consumers Union Action Fund", amount: "$1.2M" },
      { name: "Center for Responsible Lending", amount: "$0.9M" },
      { name: "National Consumer Law Center", amount: "$0.7M" },
    ],
    topCandidates: [
      { name: "Elizabeth Warren", party: "D", state: "MA", amount: "$820K" },
      { name: "Sherrod Brown", party: "D", state: "OH", amount: "$640K" },
      { name: "Bernie Sanders", party: "D", state: "VT", amount: "$580K" },
      { name: "Katie Porter", party: "D", state: "CA", amount: "$520K" },
      { name: "Richard Blumenthal", party: "D", state: "CT", amount: "$460K" },
    ],
    interestBreakdown: [
      { label: "CFPB Enforcement", pct: 30 },
      { label: "Data Privacy & Surveillance", pct: 26 },
      { label: "Product Safety (CPSC)", pct: 20 },
      { label: "Antitrust & Price-Fixing", pct: 14 },
      { label: "Payday Lending Reform", pct: 10 },
    ],
  },
  {
    name: "Housing / Homelessness / Tenant Advocacy",
    tag: "HOUSING",
    acronym: "NLIHC",
    description: "Housing and tenant advocacy organizations spend $15–$45M annually lobbying for affordable housing funding, renter protections, homelessness services, and zoning reform. The National Low Income Housing Coalition and tenant unions advocate for Section 8 expansion, just-cause eviction protections, and inclusionary zoning. The sector is often in direct conflict with the real estate and landlord lobby.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$15M–$45M",
    partySplitDem: 88,
    partySplitRep: 12,
    website: "https://nlihc.org",
    headquarters: "Washington, DC",
    industry: "housing",
    influenceScore: 28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=W",
    topPacs: [
      { name: "National Low Income Housing Coalition", amount: "$1.4M" },
      { name: "National Alliance to End Homelessness", amount: "$1.1M" },
      { name: "Tenants Together Action", amount: "$0.9M" },
      { name: "Enterprise Community Partners", amount: "$0.7M" },
      { name: "NeighborWorks America", amount: "$0.6M" },
    ],
    topCandidates: [
      { name: "Maxine Waters", party: "D", state: "CA", amount: "$420K" },
      { name: "Ilhan Omar", party: "D", state: "MN", amount: "$360K" },
      { name: "Gregory Meeks", party: "D", state: "NY", amount: "$320K" },
      { name: "Alexandria Ocasio-Cortez", party: "D", state: "NY", amount: "$300K" },
      { name: "Keith Ellison", party: "D", state: "MN", amount: "$280K" },
    ],
    interestBreakdown: [
      { label: "Section 8 & Housing Vouchers", pct: 32 },
      { label: "Homelessness Services (HUD)", pct: 26 },
      { label: "Renter Protections", pct: 22 },
      { label: "Affordable Housing Tax Credits", pct: 12 },
      { label: "Zoning & YIMBY Policy", pct: 8 },
    ],
  },
  {
    name: "Disability Rights",
    tag: "DISABILITY",
    acronym: "NCIL",
    description: "Disability rights organizations spend $10–$40M annually to protect the ADA, expand Medicaid home and community-based care, oppose cuts to SSI/SSDI, and push for accessible transportation and technology. The National Council on Independent Living, ADAPT, and the Arc lobby for full community integration and against institutionalization. The sector is bipartisan but more aligned with Democrats on funding issues.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$10M–$40M",
    partySplitDem: 72,
    partySplitRep: 28,
    website: "https://ncil.org",
    headquarters: "Washington, DC",
    industry: "disability",
    influenceScore: 28,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q",
    topPacs: [
      { name: "NCIL Disability Action Fund", amount: "$0.9M" },
      { name: "The Arc of the United States", amount: "$0.8M" },
      { name: "National Disability Rights Network", amount: "$0.7M" },
      { name: "United Spinal Association PAC", amount: "$0.5M" },
      { name: "Autism Society of America", amount: "$0.4M" },
    ],
    topCandidates: [
      { name: "Patty Murray", party: "D", state: "WA", amount: "$280K" },
      { name: "Tom Harkin", party: "D", state: "IA", amount: "$240K" },
      { name: "Bob Casey Jr", party: "D", state: "PA", amount: "$220K" },
      { name: "Chris Van Hollen", party: "D", state: "MD", amount: "$200K" },
      { name: "Jim Sensenbrenner", party: "R", state: "WI", amount: "$180K" },
    ],
    interestBreakdown: [
      { label: "Medicaid Home Care (HCBS)", pct: 32 },
      { label: "SSI / SSDI Benefits", pct: 26 },
      { label: "ADA Enforcement", pct: 22 },
      { label: "Accessible Technology", pct: 12 },
      { label: "Special Education Funding", pct: 8 },
    ],
  },
  {
    name: "Childcare / Family / Foster Care Policy",
    tag: "CHILDCARE",
    acronym: "NACCRRA",
    description: "Childcare and family advocacy organizations spend $10–$40M annually lobbying for childcare subsidies, universal pre-K, paid family leave, and foster care reform. The sector represents parents, providers, and child welfare organizations. It has grown in prominence post-pandemic as childcare costs have skyrocketed. The Child Care and Development Fund is a primary legislative target.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$10M–$40M",
    partySplitDem: 78,
    partySplitRep: 22,
    website: "https://www.naccrra.org",
    headquarters: "Washington, DC",
    industry: "childcare",
    influenceScore: 26,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=W03",
    topPacs: [
      { name: "First Focus on Children Action", amount: "$0.9M" },
      { name: "Children's Defense Fund Action", amount: "$0.8M" },
      { name: "National Association Child Care", amount: "$0.7M" },
      { name: "Zero to Three Action Network", amount: "$0.5M" },
      { name: "Annie E. Casey Foundation", amount: "$0.4M" },
    ],
    topCandidates: [
      { name: "Patty Murray", party: "D", state: "WA", amount: "$260K" },
      { name: "Kirsten Gillibrand", party: "D", state: "NY", amount: "$240K" },
      { name: "Richard Blumenthal", party: "D", state: "CT", amount: "$220K" },
      { name: "Tim Kaine", party: "D", state: "VA", amount: "$200K" },
      { name: "Lisa Murkowski", party: "R", state: "AK", amount: "$180K" },
    ],
    interestBreakdown: [
      { label: "Childcare Subsidies (CCDF)", pct: 34 },
      { label: "Universal Pre-K & Head Start", pct: 26 },
      { label: "Paid Family & Medical Leave", pct: 22 },
      { label: "Foster Care Reform", pct: 10 },
      { label: "Child Tax Credit", pct: 8 },
    ],
  },
  {
    name: "Tribal Governments / Gaming / Sovereignty",
    tag: "TRIBAL",
    acronym: "NCAI",
    description: "Tribal governments and Native American advocacy organizations spend $10–$40M annually lobbying on tribal sovereignty, gaming compacts, treaty rights, healthcare funding (IHS), and natural resource management. Tribes are among the top campaign donors in states like Oklahoma, California, and Connecticut. Tribal gaming interests sometimes conflict with commercial casino lobbies.",
    category: "lobby",
    sentiment: "neutral",
    spendRange: "$10M–$40M",
    partySplitDem: 58,
    partySplitRep: 42,
    website: "https://www.ncai.org",
    headquarters: "Washington, DC",
    industry: "tribal",
    influenceScore: 12,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=G5510",
    topPacs: [
      { name: "National Indian Gaming Assn PAC", amount: "$4.2M" },
      { name: "Chickasaw Nation PAC", amount: "$2.8M" },
      { name: "Cherokee Nation PAC", amount: "$2.4M" },
      { name: "Mashantucket Pequot Tribal PAC", amount: "$2.1M" },
      { name: "Oneida Indian Nation PAC", amount: "$1.8M" },
    ],
    topCandidates: [
      { name: "Tom Cole", party: "R", state: "OK", amount: "$580K" },
      { name: "Markwayne Mullin", party: "R", state: "OK", amount: "$520K" },
      { name: "Sharice Davids", party: "D", state: "KS", amount: "$460K" },
      { name: "Deb Haaland", party: "D", state: "NM", amount: "$420K" },
      { name: "John Barrasso", party: "R", state: "WY", amount: "$380K" },
    ],
    interestBreakdown: [
      { label: "Tribal Gaming Compacts", pct: 35 },
      { label: "Tribal Sovereignty & Self-Gov.", pct: 26 },
      { label: "IHS Healthcare Funding", pct: 20 },
      { label: "Treaty & Water Rights", pct: 12 },
      { label: "Land Trust & Reservation", pct: 7 },
    ],
  },
  {
    name: "Data Privacy / Digital Rights",
    tag: "DATA_PRIVACY",
    acronym: "EFF",
    description: "Data privacy and digital rights organizations spend $10–$40M annually lobbying for comprehensive privacy legislation, limits on surveillance, stronger encryption rights, and children's online safety protections. The Electronic Frontier Foundation, Center for Democracy & Technology, and EPIC lead the advocacy. The sector faces formidable opposition from tech giants and advertising companies that profit from data collection.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$10M–$40M",
    partySplitDem: 74,
    partySplitRep: 26,
    website: "https://www.eff.org",
    headquarters: "San Francisco, CA",
    industry: "digital_rights",
    influenceScore: 30,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=B1200",
    topPacs: [
      { name: "Electronic Frontier Foundation Action", amount: "$1.2M" },
      { name: "Center for Democracy & Technology", amount: "$0.9M" },
      { name: "EPIC Action Fund", amount: "$0.7M" },
      { name: "Mozilla Foundation Action", amount: "$0.6M" },
      { name: "Fight for the Future", amount: "$0.5M" },
    ],
    topCandidates: [
      { name: "Ron Wyden", party: "D", state: "OR", amount: "$340K" },
      { name: "Maria Cantwell", party: "D", state: "WA", amount: "$300K" },
      { name: "Roger Wicker", party: "R", state: "MS", amount: "$260K" },
      { name: "Brian Schatz", party: "D", state: "HI", amount: "$240K" },
      { name: "Marsha Blackburn", party: "R", state: "TN", amount: "$220K" },
    ],
    interestBreakdown: [
      { label: "Federal Privacy Legislation", pct: 32 },
      { label: "Surveillance & Wiretapping", pct: 26 },
      { label: "Children's Online Safety", pct: 22 },
      { label: "Encryption Rights", pct: 12 },
      { label: "Algorithmic Accountability", pct: 8 },
    ],
  },
  {
    name: "Election Reform / Democracy Reform",
    tag: "ELECTION_REFORM",
    acronym: "CLC",
    description: "Election reform and democracy advocacy groups spend $10–$40M annually on automatic voter registration, ranked choice voting, small-dollar public financing, redistricting reform, and campaign finance disclosure. The Campaign Legal Center, End Citizens United, and Common Cause are major players. The sector directly threatens the fundraising model of many incumbents, making its legislative path difficult.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$10M–$40M",
    partySplitDem: 88,
    partySplitRep: 12,
    website: "https://campaignlegal.org",
    headquarters: "Washington, DC",
    industry: "democracy",
    influenceScore: 38,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q01",
    topPacs: [
      { name: "End Citizens United PAC", amount: "$4.8M" },
      { name: "Common Cause Action Fund", amount: "$2.4M" },
      { name: "Campaign Legal Center Action", amount: "$1.8M" },
      { name: "Represent.Us PAC", amount: "$1.4M" },
      { name: "Issue One Action", amount: "$0.9M" },
    ],
    topCandidates: [
      { name: "Sheldon Whitehouse", party: "D", state: "RI", amount: "$480K" },
      { name: "John Sarbanes", party: "D", state: "MD", amount: "$420K" },
      { name: "Elizabeth Warren", party: "D", state: "MA", amount: "$380K" },
      { name: "Bernie Sanders", party: "D", state: "VT", amount: "$360K" },
      { name: "Lisa Murkowski", party: "R", state: "AK", amount: "$240K" },
    ],
    interestBreakdown: [
      { label: "Campaign Finance Disclosure", pct: 30 },
      { label: "Voter Registration & Access", pct: 26 },
      { label: "Redistricting & Gerrymandering", pct: 22 },
      { label: "Public Campaign Financing", pct: 14 },
      { label: "Ranked Choice Voting", pct: 8 },
    ],
  },
  {
    name: "Anti-Corruption / Watchdog Groups",
    tag: "ANTI_CORRUPTION",
    acronym: "CREW",
    description: "Anti-corruption and government watchdog organizations spend $5–$30M annually on ethics enforcement, lobbying disclosure reform, revolving door restrictions, and inspector general protections. CREW, POGO, OpenSecrets, and Transparency International USA are key voices. They are the most underfunded sector relative to the scale of corruption they confront, relying heavily on small donors and foundations rather than corporate backing.",
    category: "lobby",
    sentiment: "positive",
    spendRange: "$5M–$30M",
    partySplitDem: 80,
    partySplitRep: 20,
    website: "https://www.citizensforethics.org",
    headquarters: "Washington, DC",
    industry: "watchdog",
    influenceScore: 45,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/industries/indus.php?ind=Q02",
    topPacs: [
      { name: "CREW Action PAC", amount: "$1.2M" },
      { name: "POGO Action Fund", amount: "$0.8M" },
      { name: "Transparency International USA", amount: "$0.6M" },
      { name: "OpenSecrets (nonpartisan research)", amount: "$0.5M" },
      { name: "Issue One Action", amount: "$0.4M" },
    ],
    topCandidates: [
      { name: "Sheldon Whitehouse", party: "D", state: "RI", amount: "$180K" },
      { name: "Elizabeth Warren", party: "D", state: "MA", amount: "$160K" },
      { name: "Adam Schiff", party: "D", state: "CA", amount: "$140K" },
      { name: "Katie Porter", party: "D", state: "CA", amount: "$130K" },
      { name: "Mike Quigley", party: "D", state: "IL", amount: "$120K" },
    ],
    interestBreakdown: [
      { label: "Ethics & Disclosure Reform", pct: 32 },
      { label: "Revolving Door Restrictions", pct: 26 },
      { label: "Inspector General Protections", pct: 22 },
      { label: "Dark Money Disclosure", pct: 12 },
      { label: "Foreign Agent Registration", pct: 8 },
    ],
  },
  {
    name: "Party Infrastructure / Leadership PACs / Consultants",
    tag: "PARTY_INFRA",
    acronym: "DNC/RNC",
    description: "Party infrastructure spending — national committees, leadership PACs, and political consultants — represents $50–$500M+ in combined annual spending that shapes every election cycle. Leadership PACs allow individual members of Congress to raise and spend money outside campaign finance limits, creating a system of political favors. The consultant class extracts enormous fees from campaigns on both sides.",
    category: "lobby",
    sentiment: "negative",
    spendRange: "$50M–$500M+",
    partySplitDem: 50,
    partySplitRep: 50,
    website: "https://www.fec.gov",
    headquarters: "Washington, DC",
    industry: "party_politics",
    influenceScore: -20,
    dataSourceName: "OpenSecrets",
    dataSourceUrl: "https://www.opensecrets.org/parties",
    topPacs: [
      { name: "Democratic National Committee", amount: "$280M+" },
      { name: "Republican National Committee", amount: "$250M+" },
      { name: "DCCC (House Dems)", amount: "$120M+" },
      { name: "NRCC (House Reps)", amount: "$115M+" },
      { name: "Leadership PACs (combined)", amount: "$80M+" },
    ],
    topCandidates: [
      { name: "Joe Biden", party: "D", state: "DE", amount: "Unlimited" },
      { name: "Donald Trump", party: "R", state: "FL", amount: "Unlimited" },
      { name: "Mitch McConnell", party: "R", state: "KY", amount: "$18M+" },
      { name: "Chuck Schumer", party: "D", state: "NY", amount: "$16M+" },
      { name: "Kevin McCarthy", party: "R", state: "CA", amount: "$14M+" },
    ],
    interestBreakdown: [
      { label: "National Committee Operations", pct: 30 },
      { label: "Leadership PAC Transfers", pct: 26 },
      { label: "Political Consulting Fees", pct: 22 },
      { label: "Opposition Research", pct: 12 },
      { label: "Voter Data & Technology", pct: 10 },
    ],
  },
];

export async function seedLobbies(): Promise<void> {
  // Always replace lobby sectors — delete old records and insert fresh 50-sector data
  log(`Deleting existing lobby records to replace with 50-sector data...`);
  await db.execute(sql`DELETE FROM special_interest_groups WHERE category = 'lobby'`);

  log(`Seeding ${SECTORS.length} industry lobby sectors...`);

  for (const sector of SECTORS) {
    await db.execute(sql`
      INSERT INTO special_interest_groups (
        id, name, acronym, tag, description, category, sentiment,
        website, headquarters, industry,
        data_source_name, data_source_url,
        influence_score,
        spend_range, party_split_dem, party_split_rep,
        top_pacs, top_candidates, interest_breakdown,
        is_active, created_at, updated_at
      )
      VALUES (
        gen_random_uuid(),
        ${sector.name}, ${sector.acronym ?? null}, ${sector.tag},
        ${sector.description}, ${sector.category}, ${sector.sentiment},
        ${sector.website}, ${sector.headquarters}, ${sector.industry},
        ${sector.dataSourceName}, ${sector.dataSourceUrl},
        ${sector.influenceScore},
        ${sector.spendRange},
        ${sector.partySplitDem},
        ${sector.partySplitRep},
        ${JSON.stringify(sector.topPacs)}::json,
        ${JSON.stringify(sector.topCandidates)}::json,
        ${JSON.stringify(sector.interestBreakdown)}::json,
        true, NOW(), NOW()
      )
      ON CONFLICT (tag) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        sentiment = EXCLUDED.sentiment,
        spend_range = EXCLUDED.spend_range,
        party_split_dem = EXCLUDED.party_split_dem,
        party_split_rep = EXCLUDED.party_split_rep,
        top_pacs = EXCLUDED.top_pacs,
        top_candidates = EXCLUDED.top_candidates,
        interest_breakdown = EXCLUDED.interest_breakdown,
        influence_score = EXCLUDED.influence_score,
        updated_at = NOW()
    `);
  }

  log(`Lobby sector seed complete — ${SECTORS.length} sectors upserted`);
}
