import OpenAI from "openai";
import type { Representative } from "@shared/schema";

// Initialize OpenAI client only when needed to avoid startup crashes
function getOpenAIClient(): OpenAI {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY environment variable is required");
  }
  // the newest OpenAI model is "gpt-5" which was released August 7, 2025. do not change this unless explicitly requested by the user
  return new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

interface RepresentativeResponse {
  representatives: Array<{
    name: string;
    office: string;
    level: "federal" | "state" | "local";
    party?: string;
    phone?: string;
    email?: string;
    website?: string;
    address?: string;
    district?: string;
    state?: string;
  }>;
}

export async function findRepresentativesByZipCode(zipCode: string): Promise<Representative[]> {
  try {
    const openai = getOpenAIClient();
    
    const prompt = `Find all elected representatives for zip code ${zipCode}. Include federal (President, Vice President, Senators, House Representative), state (Governor, State Senator, State Representative), and local officials (Mayor, City Council, County officials) where possible.

For each representative, provide:
- Full name
- Office title (e.g., "President", "U.S. Senator", "Governor", "Mayor") 
- Level (federal, state, or local)
- Political party (if known)
- Phone number (if publicly available)
- Email address (if publicly available)
- Official website URL (if available)
- Office address (if available)
- District information (congressional district, state district, ward, etc.)
- State abbreviation

Please respond with JSON in this exact format:
{
  "representatives": [
    {
      "name": "Full Name",
      "office": "Office Title",
      "level": "federal|state|local",
      "party": "Party Name",
      "phone": "Phone Number",
      "email": "Email Address",
      "website": "Website URL",
      "address": "Office Address",
      "district": "District Info",
      "state": "State Abbreviation"
    }
  ]
}`;

    const response = await openai.chat.completions.create({
      model: "gpt-5", // the newest OpenAI model is "gpt-5" which was released August 7, 2025. do not change this unless explicitly requested by the user
      messages: [
        {
          role: "system",
          content: "You are a helpful assistant that provides accurate information about elected representatives. Respond only with valid JSON data."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      response_format: { type: "json_object" },
    });

    const result: RepresentativeResponse = JSON.parse(response.choices[0].message.content || "{}");
    
    if (!result.representatives) {
      throw new Error("Invalid response format from OpenAI");
    }

    // Convert to our Representative format
    return result.representatives.map(rep => ({
      id: "", // Will be generated by database
      name: rep.name,
      office: rep.office,
      level: rep.level,
      party: rep.party || null,
      phone: rep.phone || null,
      email: rep.email || null,
      website: rep.website || null,
      address: rep.address || null,
      photoUrl: null, // Could be enhanced later
      district: rep.district || null,
      state: rep.state || null,
      zipCodes: [zipCode], // Associate with the searched zip code
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

  } catch (error) {
    console.error("Error finding representatives:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    throw new Error(`Failed to find representatives for zip code ${zipCode}: ${errorMessage}`);
  }
}